### ISSUE TITLE
Software crashes when using the system-level back button

### ISSUE THREAD

**Issue by JXing233** [mihonapp/mihon#1573] opened 2024-12-13 12:32 UTC
### Steps to reproduce

Software crashes when using the system-level back button

### Expected behavior

。

### Actual behavior

。

### Crash logs

[
[mihon_crash_logs.txt](https://github.com/user-attachments/files/18126295/mihon_crash_logs.txt)
![Screenshot_2024-12-13-20-27-40-920_app mihon](https://github.com/user-attachments/assets/89f7f75e-3b11-426f-8e30-e8e409e86d06)
](url)

### Mihon version

0.17.1

### Android version

android14

### Device

redmik50

### Other details

Crashes every time I go back using the sidebar

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-12-13 12:34
1. Duplicate of #1278, it's already reported before as a chinaphone issue (by me), and it's pinned in the Issues page. Actually search the existing issues first before opening a new issue, and acknowledging that you did when you clearly didn't
2. Actually fill out the issue request for future issue requests

**Closed by Smol-Ame** 2024-12-13 12:34 UTC
Labels: Bug
