### ISSUE TITLE
Allow partially failed download to be marked completed

### ISSUE THREAD

**Issue by common-era** [mihonapp/mihon#1478] opened 2024-11-12 18:46 UTC
### Describe your suggested feature

When one page/image of a chapter fails to download, the entire download is failed. A nice feature to have would be an option on the 3-dot dropdown for a paused/failed download to treat it as if it completed and simply skip the missing pages like when reading the chapter from source without downloading.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-11-13 01:19
Duplicate of #587

**Closed by Smol-Ame** 2024-11-13 01:19 UTC
Labels: Feature request
