### ISSUE TITLE
Not Logging into MyAnimeList 

### ISSUE THREAD

**Issue by einstein591** [mihonapp/mihon#357] opened 2024-02-07 06:11 UTC
### Steps to reproduce

1. I select the MyAnimeList Option for Trackers
2. I log into MyAnimeList.
3. I select "Allow" on MyAnimeList to grant access to Mihon

### Expected behavior

I should see the green check near MyAnmeList, and the app should track my progress

### Actual behavior

No green check, and MyAnimeList doesn't show up as a tracking option for a manga

### Crash logs

[20240207000906_mihon_crash_logs.txt](https://github.com/mihonapp/mihon/files/14189767/20240207000906_mihon_crash_logs.txt)

### Mihon version

0.16.3

### Android version

Android 10

### Device

motorola moto e (XT2052DL)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment] 2024-02-07 06:12
Duplicate of #298. Please actually do the steps you ticked as completed on the form.
This is a MAL issue, not a Mihon issue.

**Closed** 2024-02-07 06:13 UTC
Labels: Bug
