### ISSUE TITLE
Last chapter/Chapter count on migration

### ISSUE THREAD

**Issue by BartShoot** [mihonapp/mihon#1079] opened 2024-08-05 10:39 UTC
### Describe your suggested feature

It would be great if we could see chapter count or last chapter name when migrating, maybe even compare with current latest chapter on source we are migrating from. 

It's always cumbersome to tap and hold the manga, usually refresh it too so I can see current chapter and if its up to date or behind. 

### Other details

If it seems like good first issue I could try to tackle it myself, I have some Java and Kotlin experience but on webapp side of things, not android applications.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Animeboynz** [comment] 2024-08-05 10:58
> * [x]  I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open or closed issue.

Duplicate of #1069, with is duplicate of #355 which is a duplicate of #324. 
My 13th reason why. XD

**Closed** 2024-08-05 11:13 UTC
Labels: Feature request
