### ISSUE TITLE
Read comicxml from chapter folder for local source

### ISSUE THREAD

**Issue by sadboy889** [mihonapp/mihon#1174] opened 2024-08-28 22:08 UTC
### Describe your suggested feature

read comicxml from
/local/manga/chapter
instead of /local/manga for local source

i had to move comicxml from chapter folder manually to manga folder before the app can detect it, which is too exhausting 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-08-28 22:24
Duplicate of #100

**Closed by Smol-Ame** 2024-08-28 22:24 UTC
Labels: Feature request
