### ISSUE TITLE
Merge comic double-page display on tablet screens

### ISSUE THREAD

**Issue by komooki** [mihonapp/mihon#1355] opened 2024-10-22 01:43 UTC
### Describe your suggested feature

This software is already perfect, but there is a function on the tablet that can make it even more perfect, which is to merge the two pages of the comic and display it, I wonder if this feature can be added in the update

### Other details

![Screenshot_2024-10-22-09-34-24-224_app komikku](https://github.com/user-attachments/assets/2aa2edcb-4695-4feb-99d1-b4fdf0cac573)
![Screenshot_2024-10-22-09-39-39-654_app komikku](https://github.com/user-attachments/assets/0089cd9e-24a8-4d2a-bce3-5ab2fe42d1c2)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-10-22 02:23
Duplicate of #28

**Closed by Smol-Ame** 2024-10-22 02:23 UTC
Labels: Feature request
