### ISSUE TITLE
Please Add Volume Support On Your App Alongside With Chapters

### ISSUE THREAD

**Issue by BloopSmasher** [mihonapp/mihon#434] opened 2024-02-20 04:46 UTC
### Describe your suggested feature

Your app mihon and tachiyomi also does not provide support for downloading Manga in **volumes** they only support for downloading Mangal chapters, please add a feature for downloading Manga in volume instead of chapters

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment] 2024-02-20 04:58
Mihon can only offer for download what sources provide. There isn't any real way to know if a source is providing volume or chapter files, or any way to find out how many chapters are in a volume for a given series (it might even matter which physical edition the volume is based on).

What exactly are you envisioning Mihon to do when you say "downloading volumes"? And what use case do you have for it if it did exist?

**Comment by BloopSmasher** [comment] 2024-02-20 06:48
There is one source which provide volume support, which is mangareader.

**Comment by AntsyLich** [comment] 2024-05-05 10:15
Duplicate of #15

**Closed by AntsyLich** 2024-05-05 10:15 UTC
Labels: Feature request
