### ISSUE TITLE
Add ability to set default or track reading mode by category

### ISSUE THREAD

**Issue by jobu01** [mihonapp/mihon#1186] opened 2024-09-02 21:25 UTC
### Describe your suggested feature

Add the ability to set the reading mode per category or have each category track the last reading mode selected and use that for new content added.

I have a mix of media that is either long strip webtoon style and comic books like pages.  Currently, I use the global default reading mode setting that fits the majority of my content.  Then, I need to manually set the mode for each new entry to the other mode as necessary.  If we can make use of categories to group this setting, I believe it would improve usability.  This would allow us to easily group like content together sharing the same default settings for that category.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment] 2024-09-02 21:36
> - [x] I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open or closed issue.

Liar liar pants on fire
#150 #247

**Comment by MajorTanya** [comment] 2024-09-02 21:39
Duplicate of #247

**Closed by MajorTanya** 2024-09-02 21:39 UTC
Labels: Feature request
