### ISSUE TITLE
Dual-page reading mode

### ISSUE THREAD

**Issue by iAmGing3rJo3** [mihonapp/mihon#589] opened 2024-03-28 20:48 UTC
### Describe your suggested feature

An available option for showing two pages at once instead of just one. More useful on foldables and tablets. Example from tachiyomij2k. 
![Screenshot_20240328-164714](https://github.com/mihonapp/mihon/assets/31388461/b78c722a-e847-489c-ae5d-4e64f3125590)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by eroubisu** [comment] 2024-08-11 13:35
really need this

**Comment by Smol-Ame** [comment] 2024-08-19 10:35
Closing as a duplicate of #28

**Closed by Smol-Ame** 2024-08-19 10:35 UTC
Labels: Feature request
