### ISSUE TITLE
"Update library\category" not working

### ISSUE THREAD

**Issue by CinderBH** [mihonapp/mihon#413] opened 2024-02-17 17:22 UTC
### Steps to reproduce

When I try to update the whole library from the main tab nothing happens, but updating individual series in their own page works. As far as I can tell, the app has all required permissions.

### Expected behavior

Selecting "update library\category" from the main tab or swiping down updates all series in the same, with a notification popping up.

### Actual behavior

Neither happens.

### Crash logs

[mihon_crash_logs(1).txt](https://github.com/mihonapp/mihon/files/14319638/mihon_crash_logs.1.txt)

### Mihon version

0.16.3

### Android version

Android 14

### Device

Samsung Galaxy A14 5G

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by CinderBH** [comment] 2024-02-17 17:27
Actually, I checked off "skip series with unread chapters" and the result was the same.

**Comment by CinderBH** [comment] 2024-02-17 17:35
The thing is, if it didn't work now when it had unloaded chapters, how am I sure it'll work at the predicted time? That's my concern.

**Comment by MajorTanya** [comment] 2024-02-17 18:16
If you so desperately need all chapters immediately all the time, you can always go check manually

**Comment by CinderBH** [comment] 2024-02-17 19:10
> If you so desperately need all chapters immediately all the time, you can always go check manually

That's... that's why I posted an issue, global manual check isn't working.

**Comment by MajorTanya** [comment] 2024-03-06 16:16
Closing as won't fix as it's the intended behaviour of predictive updates. If you have further questions about this, join the Support Discord.

**Closed by MajorTanya** 2024-03-06 16:16 UTC
Labels: Bug
