### ISSUE TITLE
Download animation UI is not properly rendered correctly on older android versions

### ISSUE THREAD

**Issue by apacheit2** [mihonapp/mihon#978] opened 2024-07-02 11:13 UTC
### Steps to reproduce

1. Find any comic chapters
2. Download certain chapter
3. Then you can see the download ui is not properly rendered
![IMG_20240702_190657](https://github.com/mihonapp/mihon/assets/109053229/909ebfbe-8a67-4027-9ad2-fa5b3bd79cb1)

### Expected behavior

Supposed the animation UI of download icon is matched by its design

### Actual behavior

The download animation is not properly rendered when downloading certain chapters.

### Crash logs

content://app.mihon.provider/ext_cache_files/mihon_crash_logs.txt

### Mihon version

0.16.5

### Android version

Android 9

### Device

realme C2

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Animeboynz** [comment] 2024-07-02 11:36
> content://app.mihon.provider/ext_cache_files/mihon_crash_logs.txt 😒

Probably a duplicate of #678 #648 #644 
Try the [Preview build](https://github.com/mihonapp/mihon-preview/releases) and see if its fixed.

**Comment by apacheit2** [comment] 2024-07-02 11:50
> > content://app.mihon.provider/ext_cache_files/mihon_crash_logs.txt 😒
> 
> Probably a duplicate of #678 #648 #644 Try the [Preview build](https://github.com/mihonapp/mihon-preview/releases) and see if its fixed.

nope, its not duplicate. mine is glitchy 

https://github.com/mihonapp/mihon/assets/109053229/a6ced029-20bc-4d1c-926a-8bb443142b14

**Closed** 2024-07-02 11:49 UTC
Labels: Bug

**Comment by AntsyLich** [comment] 2024-07-02 11:52
What about in preview?

**Comment by apacheit2** [comment] 2024-07-02 11:55
> What about in preview?

I'm on stable version but idk if it's fixed on preview.

**Comment by AntsyLich** [comment] 2024-07-02 12:09
> idk if it's fixed on preview.

check it then?

**Comment by Animeboynz** [comment] 2024-07-02 12:09
My guy, please just download the [Preview build](https://github.com/mihonapp/mihon-preview/releases) from here and download a chapter so see if the error still exists
