### ISSUE TITLE
Big empty space under the navigation bar 💀

### ISSUE THREAD

**Issue by nobSEIFO** [mihonapp/mihon#1384] opened 2024-10-26 21:12 UTC
### Steps to reproduce

Just open the app

### Expected behavior

No space between the bottom edge of screen and the star of the navigation bar

### Actual behavior

Big empty space under the navigation bar 
![Screenshot_20241026-215810_Mihon](https://github.com/user-attachments/assets/b90e0956-fbb4-4d22-9051-3633e311151d)

### Crash logs

No 

### Mihon version

0.17.0

### Android version

Android 8

### Device

Galaxy s7

### Other details

![Screenshot_20241026-220956_Kiwi Browser](https://github.com/user-attachments/assets/8ade8b08-4f63-4ced-b7f9-373711da65d9)
My phone has physical back,recent apps, home buttons

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment] 2024-10-26 21:14
Duplicate of #1330.

Please actually do what you confirmed in the acknowledments section and check other issues before opening new ones.

**Closed by MajorTanya** 2024-10-26 21:14 UTC
Labels: Bug
