### ISSUE TITLE
Auto-slide feature for Mihon's "Long Strip" Reading Mode

### ISSUE THREAD

**Issue by Shirou27** [mihonapp/mihon#232] opened 2024-01-25 14:05 UTC
I have a cool idea for Mihon! What if you add an auto-slide or auto-scroll feature for "Long Strip" mode with customizeable speed? We could then totally read manhwa or manga hands-free, we can multitask or even eat while reading manhwa/manga as if watching anime, it would be awesome. Please give it some thought!

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-08-16 02:12
Closing since it's just a duplicate of #10

**Closed by Smol-Ame** 2024-08-16 02:12 UTC
Labels: Feature request
