### ISSUE TITLE
f-droid 

### ISSUE THREAD

**Issue by cannnAvar** [mihonapp/mihon#346] opened 2024-02-04 15:33 UTC
### Describe your suggested feature

Can we get updates from fdroid.
on fdroid there is tachiyomi's old apk.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment] 2024-02-04 18:04
Duplicate of #1

**Closed** 2024-02-04 19:56 UTC
Labels: Feature request

**Comment by cannnAvar** [comment] 2024-02-04 19:58
> Duplicate of #1

Sory i didn't see that one
