### ISSUE TITLE
Add a "disable zoom in" option in reader 

### ISSUE THREAD

**Issue by xdeiimoss** [mihonapp/mihon#1529] opened 2024-11-30 17:12 UTC
### Describe your suggested feature

There's a disable zoom out option, there should be one for zoom in as well

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2024-11-30 17:22
Duplicate of #1397

**Closed by AntsyLich** 2024-11-30 17:22 UTC
Labels: Feature request
