### ISSUE TITLE
Long strip sometime showing blank image

### ISSUE THREAD

**Issue by Erioria** [mihonapp/mihon#1436] opened 2024-11-02 19:06 UTC
### Steps to reproduce

Reading with longstrip mode

### Expected behavior

![Screenshot_20241103-020206](https://github.com/user-attachments/assets/72da115f-3a4b-4962-98b4-85ca36fce7ab)

### Actual behavior

![Screenshot_20241103-020200](https://github.com/user-attachments/assets/b53b6ad3-119e-4f4d-b82b-95ae5eb27f80)

### Mihon version

0.17.0

### Android version

android 10

### Device

Sony xz2 premium

### Other details

Strangely enough, turning on crop borders seem to fix it sometime, did i need to including the log for this issue?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Animeboynz** [comment] 2024-11-02 21:37
Technically a duplicate of https://github.com/mihonapp/mihon/issues/1398 but try and see if the [latest preview](https://github.com/mihonapp/mihon-preview/releases/tag/r6990) works for you, there should be a setting called alwaysUseSSIVToDecode in the advanced settings.

**Comment by Erioria** [comment] 2024-11-02 23:55
Thanks for the reply, the issue is still occured on my device unfortunately, even when i turn on alwaysUseSSIVToDecode option
![Screenshot_20241103-064828](https://github.com/user-attachments/assets/3658fcb8-d887-476f-9c60-4995ce7277a8)

**Comment by ChriszZ8** [comment] 2024-11-07 19:58
it's a bug because some devices don't support 32 Bit Permanent Color. This is a new feature of Mihon/TachiyomiSY so there are some devices that experience this bug but when installing Mihon 16.5 it's normal because the 32 bit color feature is disabled/turn off by default 

Until now I still use the previous stable version, not 17.0 because 32 bit color permanent. 🗿

**Comment by AntsyLich** [comment] 2024-11-08 06:39
> it's a bug because some devices don't support 32 Bit Permanent Color. This is a new feature of Mihon/TachiyomiSY so there are some devices that experience this bug but when installing Mihon 16.5 it's normal because the 32 bit color feature is disabled/turn off by default
> 
> Until now I still use the previous stable version, not 17.0 because 32 bit color permanent. 🗿

32 Bit color was permanently enabled in 0.16.5 so don't start facts when you know jack shit.

**Comment by Erioria** [comment] 2024-11-08 10:10
> it's a bug because some devices don't support 32 Bit Permanent Color. This is a new feature of Mihon/TachiyomiSY so there are some devices that experience this bug but when installing Mihon 16.5 it's normal because the 32 bit color feature is disabled/turn off by default
> 
> Until now I still use the previous stable version, not 17.0 because 32 bit color permanent. 🗿


I dont think that the case here , the image will showed up if i change the reading mode to other than long strip / long strip with gaps if it the color that causing the problem , i dont think it will showed the image at all even when you change the reading mode.
And someone already found and fix the problem

**Closed** 2024-11-20 11:56 UTC
Labels: Bug
