### ISSUE TITLE
Read volumes on local source

### ISSUE THREAD

**Issue by HanaO00** [mihonapp/mihon#717] opened 2024-04-26 13:36 UTC
### Describe your suggested feature

Hello,

Is it possible to add a function in the local source to be able to sort by volume_x like chapter_x knowing that the scans are in volume?

Being able to read in PDF would be nice too

Thanks

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2024-05-05 10:15
Duplicate of #15 for volume. As for PDF support the current decision is no.

**Closed by AntsyLich** 2024-05-05 10:15 UTC
Labels: Feature request
