### ISSUE TITLE
Can't share data to my  anime list

### ISSUE THREAD

**Issue by Leon-san** [mihonapp/mihon#1231] opened 2024-09-17 00:08 UTC
### Steps to reproduce

- open app
- settings
- connect with mal and other service
- authentication it's ok
- back to app and doesn't connect to my account of mal

### Expected behavior

Log in and start to enjoy the syncro of the manga

### Actual behavior

After authentication you return ti the app but the app doesn't respond immidiatly and don't connect the account

### Mihon version

0.16.5

### Android version

10

### Device

One plus 5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-09-17 02:49
Duplicate of many, #794 for example

Search the existing issues (both open & closed) before making a new one, and acknowledging that you did when you clearly didn't.

For Mihon to connect to MyAnimeList, you need to do the following:
* Update your app to Mihon Stable 0.16.5 (or the equivalent Mihon Beta version), which you already are on
* __Also__, you need to change your user-agent in Mihon Settings > Advanced to something else, learn more about it through this link: https://mihon.app/docs/guides/troubleshooting/#changing-your-user-agent

Come to the Mihon Discord support channel if you have any questions/issues, for this issue or any other minor issues in the future

**Closed by Smol-Ame** 2024-09-17 02:49 UTC
Labels: Bug

**Comment by Leon-san** [comment] 2024-09-17 16:16
Hi,
thanks for reply me, lesson learned.


Il giorno mar 17 set 2024 alle ore 04:50 Smol Ame ***@***.***>
ha scritto:
