### ISSUE TITLE
Ability to edit manga status

### ISSUE THREAD

**Issue by Xori71** [mihonapp/mihon#782] opened 2024-05-11 01:45 UTC
### Describe your suggested feature

(If this is already included in [this](https://github.com/mihonapp/mihon/pull/398) pull request, then please mark the feature request as closed)

It would be useful if you could let us change the manga status freely, as some sources don’t always update it correctly for some manga. The main reason why I want this added is to help with library updates (Reduce the total sum of manga being updated) in case one hasn’t separated their manga into many categories. (Basically so the third smart updates parameter works for every entry it should normally apply to)

### Other details

None.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment] 2024-05-11 01:56
I would've assumed status was included in the mentioned PR given the exchange in the Discord channel back then (and how SY does allow editing it), but it [doesn't seem to be the case](https://github.com/mihonapp/mihon/pull/398/files#diff-927e3ccad65a0f9fb975a8e7f4df636bab724be73bf942bcb2b3ecfe722cdd97R69)

**Comment by MajorTanya** [comment] 2024-05-11 02:38
The number of support requests for missing updates because they marked it as completed just because the series has finished publishing but not translating will be wild.
It'd still be nice to have, I agree

**Comment by BrutuZ** [comment] 2024-05-11 02:58
I like to think there's very little overlap between people who would bother to edit the status and not know it's a Smart Updates parameter.
Not optimistic enough to believe it's a two circles Venn diagram because people will be people, but still.

**Comment by Xori71** [comment] 2024-05-11 11:29
> The number of support requests for missing updates because they marked it as completed just because the series has finished publishing but not translating will be wild. It'd still be nice to have, I agree

I am not so sure. J2K offered the option and I never saw people complaining about missing updates.

**Comment by Hinalover** [comment] 2024-05-14 13:47
I also would like to support this feature. Have a situation where a site has marked a series as complete even though the original series as well as the translators are both releasing new chapters each week.

**Comment by AntsyLich** [comment] 2024-08-25 14:05
Marking as a duplicate of #5

**Closed by AntsyLich** 2024-08-25 14:05 UTC
Labels: Feature request
