### ISSUE TITLE
Backups by category similar to updates

### ISSUE THREAD

**Issue by BankOfNothing** [mihonapp/mihon#389] opened 2024-02-13 17:20 UTC
### Describe your suggested feature

If you have a massive library backups cease to work and it makes a size 0 file.  If we can make backups by category like the update system so we can backup our libraries piecemeal the issue will be mitigated.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment] 2024-02-13 18:04
How massive is your library? I've seen people with several thousand entries have no issues with creating backups. Maybe the problem of your 0 size backup is a different one that's not got to do with the library size.

**Comment by BankOfNothing** [comment] 2024-02-13 22:17
> How massive is your library? I've seen people with several thousand entries have no issues with creating backups. Maybe the problem of your 0 size backup is a different one that's not got to do with the library size.

Over ten thousand... The issue has been around for a long time even with the past app. I think they improved it because several thousand used to be the limit but I guess my library grew too large lol. I think it's a size issue because the only way for me to migrate my library to Mihon was to shrink the file size by transferring the entire library with no history attached. Then deleting the rest of the library and transferring over only the full history of my currently reading category still numbering quite a bit. So I've lost the history of everything except what I'm currently reading. It's still a useful feature to have if you want to transfer parts of your library for whatever reason.

**Comment by MajorTanya** [comment] 2024-02-14 18:22
That is a lot of entries but still shouldn't cause a 0-size backup file. I'm sorry for your already deleted data but next time you encounter such an issue, try the support Discord (or an issue if you don't have Discord) for help with that first, we might have been able to save that data somehow in the end.

I think the core issue here is the fact that very large libraries fail during the backup creation process. Did you ever get some sort of error message or crash screen when you tried to create a backup back then? If so, do you remember what kind of error it was? If you don't, are you still able to reproduce this issue with your large library or is the issue gone now?

**Comment by Smol-Ame** [comment] 2024-08-16 08:23
Closing since it's a duplicate of #38

**Closed by Smol-Ame** 2024-08-16 08:23 UTC
Labels: Feature request
