### ISSUE TITLE
Can't add MyAnimeList tracker

### ISSUE THREAD

**Issue by ORLOX93** [mihonapp/mihon#424] opened 2024-02-18 14:18 UTC
### Steps to reproduce

1. Go to more
2. Go to settings
3. Go to tracking
4. Press on MyAnimeList to add/link an account
5. Log into the MyAnimeList website
6. Press allow

### Expected behavior

After pressing allow, there shoukd be a green tick next to "MyAnimeList"

### Actual behavior

After pressing allow, Mihon starts loading (for like a minute) until it gives up and never actually adds the tracker.

### Mihon version

0.16.3

### Android version

Android 8

### Device

Huawei T5 tablet

### Other details

This only happens with MyAnimeList, the other trackers work just fine.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [x] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment] 2024-02-18 14:20
Known issue, duplicate of #298, and it's on MAL's end, not Mihon's

**Closed by MajorTanya** 2024-02-18 14:20 UTC
Labels: Bug

**Comment by ORLOX93** [comment] 2024-02-19 04:12
I did search for related issues and got no matches, but i may have spelled it wrong or something 🤔

**Comment by dtantono** [comment] 2024-03-06 01:14
@ORLOX93 I have same issue as well with error 500. Let's wait for a couple of days and then if this does not work. we can reopened it again

**Comment by dtantono** [comment] 2024-03-06 01:25
Change user agent seems new workaround to me. wdym?
![Screenshot_20240306-102354](https://github.com/mihonapp/mihon/assets/29157187/247d2f78-32c4-4195-9500-ec6fc1b6a6d7)
![Screenshot_20240306-102345](https://github.com/mihonapp/mihon/assets/29157187/7d9638ff-c739-4b1c-a1d9-c687362a23de)

![Screenshot_20240306-102403](https://github.com/mihonapp/mihon/assets/29157187/edeadb52-12f3-4327-90df-4e9c7d908206)

**Comment by ORLOX93** [comment] 2024-03-06 01:34
> @ORLOX93 I have same issue as well with error 500. Let's wait for a couple of days and then if this does not work. we can reopened it again

change your default user-agent  (go to Settings > Advanced) and paste this: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/120.0

**Comment by dtantono** [comment] 2024-03-06 01:43
Yeah I changed the user agent from default setting on Settings -> Advanced to Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

it works again.
