### ISSUE TITLE
Default reader mode

### ISSUE THREAD

**Issue by pathania07** [mihonapp/mihon#1581] opened 2024-12-16 16:56 UTC
### Describe your suggested feature

 the feature I'm requesting is somewhat similar like having different reading modes in different categories so it can be more convenient 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.17.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment] 2024-12-16 17:03
Duplicate of #247

**Closed by Seishirou101** 2024-12-16 17:03 UTC
Labels: Feature request
