### ISSUE TITLE
Myanimelist does not allow me to log back in

### ISSUE THREAD

**Issue by masdabazz** [mihonapp/mihon#344] opened 2024-02-04 13:05 UTC
### Steps to reproduce

Go to tracking in settings and click on MyAnimeList. It takes you to the website where it will say allow.

### Expected behavior

Links successfully and a green checkmark appears next to MyAnimeList in mihon.

### Actual behavior

Send you back to the app with no change, and when you go back to the website it just says bad request

### Mihon version

0.16.3

### Android version

Andriod 12

### Device

Redmi Note 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment] 2024-02-04 13:15
Are you getting some sort of HTTP error code like 403 or 503? If so, this is probably a duplicate of #298 and I'll close this issue as such. MAL is currently experiencing difficulties in their API.

If it's not that and you're absolutely sure your issue is different, feel free to comment again and we can see what is going on.

**Closed** 2024-02-04 13:15 UTC
Labels: Bug
