### ISSUE TITLE
The app crashes when changing the book's category.

### ISSUE THREAD

**Issue by Godeau233** [mihonapp/mihon#289] opened 2024-01-30 13:19 UTC
### Steps to reproduce

Delete books from Library or chang the book's category

### Expected behavior

The corresponding books should be deleted.

### Actual behavior

The app crashes after deleting the books.

### Crash logs

Android version: 14 (SDK 34; build UKQ1.230804.001 release-keys)
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: socrates (socrates)
Device model: 22127RK46C
WebView: Android System WebView 117.0.5938.60

--------- beginning of main
01-30 21:04:26.123  8904  8974 E OpenGLRenderer: Unable to match the desired swap behavior.
01-30 21:05:03.998  8904  8974 E OpenGLRenderer: Unable to match the desired swap behavior.
01-30 21:05:11.131  8904  8974 E OpenGLRenderer: Unable to match the desired swap behavior.
01-30 21:05:18.384  8904  8974 E OpenGLRenderer: Unable to match the desired swap behavior.
01-30 21:05:25.063  8904  8904 E ImeBackDispatcher: Ime callback not found. Ignoring unregisterReceivedCallback. callbackId: 181393636
01-30 21:05:37.077  8904  8974 E OpenGLRenderer: Unable to match the desired swap behavior.
01-30 21:05:42.990  8904  8974 E OpenGLRenderer: Unable to match the desired swap behavior.
01-30 21:05:43.696  8904  8974 E OpenGLRenderer: Unable to match the desired swap behavior.
01-30 21:05:45.147  8904  8904 E ImeBackDispatcher: Ime callback not found. Ignoring unregisterReceivedCallback. callbackId: 181393636
01-30 21:05:47.139  8904  8974 E OpenGLRenderer: Unable to match the desired swap behavior.
01-30 21:05:47.932  8904  8974 E OpenGLRenderer: Unable to match the desired swap behavior.
01-30 21:05:51.977  8904  8904 E ImeBackDispatcher: Ime callback not found. Ignoring unregisterReceivedCallback. callbackId: 181393636
01-30 21:06:03.344  8904  9382 E DocumentsContractApi21: Failed to createFile
01-30 21:06:03.344  8904  9382 E DocumentsContractApi21: java.lang.IllegalStateException: Failed to mkdir /storage/emulated/0/Tachiyomi/downloads
01-30 21:06:03.344  8904  9382 E DocumentsContractApi21: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3065)
01-30 21:06:03.344  8904  9382 E DocumentsContractApi21: 	at android.os.Parcel.createException(Parcel.java:3041)
01-30 21:06:03.344  8904  9382 E DocumentsContractApi21: 	at android.os.Parcel.readException(Parcel.java:3024)
01-30 21:06:03.344  8904  9382 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
01-30 21:06:03.344  8904  9382 E DocumentsContractApi21: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
01-30 21:06:03.344  8904  9382 E DocumentsContractApi21: 	at android.content.ContentProviderProxy.call(ContentProviderNative.java:786)
01-30 21:06:03.344  8904  9382 E DocumentsContractApi21: 	at android.content.ContentResolver.call(ContentResolver.java:2469)
01-30 21:06:03.344  8904  9382 E DocumentsContractApi21: 	at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1380)
01-30 21:06:03.344  8904  9382 E DocumentsContractApi21: 	at logcat.ThrowablesKt.createFile(Unknown Source:4)
01-30 21:06:03.344  8904  9382 E DocumentsContractApi21: 	at com.hippo.unifile.TreeDocumentFile.createDirectory(Unknown Source:29)
01-30 21:06:03.344  8904  9382 E DocumentsContractApi21: 	at tachiyomi.domain.storage.service.StorageManager.getDownloadsDirectory(Unknown Source:6)
01-30 21:06:03.344  8904  9382 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.data.download.DownloadProvider.findSourceDir(Unknown Source:7)
01-30 21:06:03.344  8904  9382 E DocumentsContractApi21: 	at eu.kanade.tachiyomi.source.AndroidSourceManager$registerStubSource$1.invokeSuspend(Unknown Source:117)
01-30 21:06:03.344  8904  9382 E DocumentsContractApi21: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
01-30 21:06:03.344  8904  9382 E DocumentsContractApi21: 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:110)
01-30 21:06:03.344  8904  9382 E DocumentsContractApi21: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(Unknown Source:3)
01-30 21:06:03.344  8904  9382 E DocumentsContractApi21: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
01-30 21:06:03.344  8904  9382 E DocumentsContractApi21: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
01-30 21:06:03.344  8904  9382 E DocumentsContractApi21: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:62)
01-30 21:06:10.241  8904  8974 E OpenGLRenderer: Unable to match the desired swap behavior.
01-30 21:06:11.029  8904  8974 E OpenGLRenderer: Unable to match the desired swap behavior.
01-30 21:06:57.102  8904  8974 E OpenGLRenderer: Unable to match the desired swap behavior.
01-30 21:07:00.351  8904  8974 E OpenGLRenderer: Unable to match the desired swap behavior.
01-30 21:07:11.931  8904  8974 E OpenGLRenderer: Unable to match the desired swap behavior.
01-30 21:07:16.342  8904  8974 E OpenGLRenderer: Unable to match the desired swap behavior.
01-30 21:07:25.165  8904  8974 E OpenGLRenderer: Unable to match the desired swap behavior.
01-30 21:07:26.770  8904  8974 E OpenGLRenderer: Unable to match the desired swap behavior.
01-30 21:07:26.784  8904  8974 E OpenGLRenderer: Unable to match the desired swap behavior.
01-30 21:07:26.804  8904  8974 E OpenGLRenderer: Unable to match the desired swap behavior.
01-30 21:07:27.042  8904  8974 E OpenGLRenderer: Unable to match the desired swap behavior.
01-30 21:07:27.430  8904  8974 E OpenGLRenderer: Unable to match the desired swap behavior.
01-30 21:07:28.061  8904  8974 E OpenGLRenderer: Unable to match the desired swap behavior.
01-30 21:07:28.600  8904  8904 E DecorView[]: Destroying unexpected ActionMode instance of TYPE_FLOATING; com.android.internal.view.FloatingActionMode@48131db was not the current floating action mode! Expected null
01-30 21:07:38.247  8904  8974 E libEGL  : pre_cache appList: com.sina.weibo,com.ss.android.article.news,com.taobao.taobao,com.smile.gifmaker,com.ss.android.ugc.aweme,com.tencent.mm,tv.danmaku.bili,
01-30 21:07:42.639  8904  8974 E OpenGLRenderer: Unable to match the desired swap behavior.
01-30 21:07:48.186  8904  8974 E OpenGLRenderer: Unable to match the desired swap behavior.
01-30 21:07:49.424  8904  9378 E CursorWindow: Failed to read row 1197, column 0 from a CursorWindow which has 1197 rows, 29 columns.
01-30 21:07:49.529 11594 11594 E n:error_handler: Not starting debugger since process cannot load the jdwp agent.
01-30 21:07:49.589 11594 11619 E SQLiteLog: (283) recovered 983 frames from WAL file /data/data/app.mihon/databases/tachiyomi.db-wal
01-30 21:07:50.036 11594 11622 E libEGL  : pre_cache appList: com.sina.weibo,com.ss.android.article.news,com.taobao.taobao,com.smile.gifmaker,com.ss.android.ugc.aweme,com.tencent.mm,tv.danmaku.bili,
01-30 21:07:50.051 11594 11622 E OpenGLRenderer: Unable to match the desired swap behavior.
01-30 21:07:50.060 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:50.068 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:50.069 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:50.074 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:50.078 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:50.079 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.606 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.612 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.613 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.613 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.615 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.615 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.628 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.629 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.629 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.645 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.647 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.647 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.663 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.664 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.665 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.672 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.672 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.673 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.678 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.679 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.679 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.685 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.686 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.686 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.700 12265 12265 E app.mihon: Not starting debugger since process cannot load the jdwp agent.
01-30 21:07:51.702 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.703 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.703 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.719 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.719 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.720 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.735 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.736 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.736 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.752 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.752 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.753 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.769 12265 12324 E SQLiteLog: (5) statement aborts at 2: [PRAGMA journal_mode=TRUNCATE] database is locked
01-30 21:07:51.769 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.773 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.773 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.779 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.780 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.781 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.787 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.788 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.789 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.797 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.798 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.798 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.804 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.805 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.805 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.812 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.813 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.813 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.820 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.821 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.821 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.829 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.829 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.830 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.837 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.838 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.838 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.845 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.846 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.846 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.854 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.854 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.855 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.862 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.863 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.863 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.870 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.871 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.871 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.878 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.879 12265 12356 E chromium: [0130/210751.876801:ERROR:variations_seed_loader.cc(69)] Failed to open file for reading. Errno: 2
01-30 21:07:51.879 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.879 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.887 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.887 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.888 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.895 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.896 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.896 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.903 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.904 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.904 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.912 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.912 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.913 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.920 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.921 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.921 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.928 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:51.929 11594 11622 E LB      : fail to open file: No such file or directory
01-30 21:07:52.205 12265 12327 E libEGL  : pre_cache appList: com.sina.weibo,com.ss.android.article.news,com.taobao.taobao,com.smile.gifmaker,com.ss.android.ugc.aweme,com.tencent.mm,tv.danmaku.bili,
01-30 21:07:52.221 12265 12327 E OpenGLRenderer: Unable to match the desired swap behavior.
01-30 21:07:52.803 12265 12668 E SQLiteLog: (284) automatic index on C(manga_id)
01-30 21:07:52.803 12265 12668 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
01-30 21:07:53.536 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.557 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.558 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.560 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.562 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.562 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.566 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.570 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.570 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.572 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.574 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.575 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.580 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.581 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.582 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.589 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.590 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.590 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.597 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.598 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.599 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.606 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.608 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.608 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.614 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.615 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.616 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.622 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.623 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.623 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.630 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.631 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.631 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.639 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.640 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.640 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.647 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.648 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.649 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.655 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.656 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.656 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.663 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.664 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.665 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.672 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.673 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.673 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.681 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.686 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.686 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.689 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.691 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.692 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.696 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.698 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.698 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.706 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.708 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.708 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.716 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.718 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.719 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.722 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.723 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.723 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.730 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.732 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.732 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.739 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.741 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.741 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.748 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.750 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.751 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.756 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.758 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.758 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.764 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.766 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.767 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.772 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.774 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.775 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.780 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.782 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.783 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.789 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.791 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.792 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.797 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.799 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.800 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.804 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.805 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.806 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.813 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.814 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.815 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.821 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:07:53.823 12265 12327 E LB      : fail to open file: No such file or directory
01-30 21:08:03.467 12265 12327 E OpenGLRenderer: Unable to match the desired swap behavior.
01-30 21:08:04.670 12265 12623 E CursorWindow: Failed to read row 1197, column 0 from a CursorWindow which has 1197 rows, 29 columns.
01-30 21:08:04.744 11594 11622 E OpenGLRenderer: Unable to match the desired swap behavior.

### Mihon version

The version is 0.16.3, but this issue has also been observed in previous versions.

### Android version

14

### Device

Redmi k60

### Other details

In past versions, this issue would occur but not frequently. Now, the app often crashes whenever a book is deleted from library or when one category is removed from a book that is associated with two or more categories.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by THElegend5** [comment] 2024-01-30 15:00
Duplicate of #93

**Comment by WGmg23** [comment] 2024-01-30 16:33
upload like an file

**Closed** 2024-01-31 22:39 UTC
Labels: Bug
