### ISSUE TITLE
"Open With Mihon" option for files

### ISSUE THREAD

**Issue by LadyHaywood** [mihonapp/mihon#1323] opened 2024-10-14 00:20 UTC
### Describe your suggested feature

I would like to be able to open local manga files with Mihon by default directly from my home launcher. Right now, when long pressing on a manga (epub & cbz) I don't have the option to open them with any Mihon app. 
![Screenshot_20241013-200931](https://github.com/user-attachments/assets/51b83329-1d1f-4539-931d-620071ec00da)

### Other details

I get that this isn't much a needed or thought about thing since this app is made for phone/tablet use, not necessarily e-readers. But for e-readers that use "book library display" home launcher having the feature would be nice.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-10-14 00:36
Duplicate of #345

**Closed by Smol-Ame** 2024-10-14 00:36 UTC
Labels: Feature request
