### ISSUE TITLE
App loops when opened

### ISSUE THREAD

**Issue by vpagini** [mihonapp/mihon#624] opened 2024-04-05 22:16 UTC
### Steps to reproduce

Opening the app

### Expected behavior

The app should open

### Actual behavior

The app loops an error message

### Crash logs

![Screenshot_20240406-001025](https://github.com/mihonapp/mihon/assets/9462204/0b419b62-8eef-4fd7-b9a8-a3059375f8aa)
 I can't export them because the app loops the message so fast it's impossible to press the button

### Mihon version

0.16.4

### Android version

Android 14

### Device

Pixel 6a

### Other details

I've tried forcing it to stop, erasing the cache and removing the app altogether and then re-installing it but nothing changes

The app was firstly installed some weeks ago. I've configured the extension and for an evening it worked fine. I did not open ot for a few weeks and then I found the bug.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by PennyJim** [comment] 2024-04-05 22:19
Common issue, see #623 (the latest copy I saw)

**Comment by MajorTanya** [comment] 2024-04-06 01:27
@vpagini See above replies, and in future please check the other existing issues first (or ask in the Discord server) before opening an issue 👍 
For this problem, there are at least #623, #616, #582, and #364.

Closing as duplicate of any of those.

**Closed by MajorTanya** 2024-04-06 01:27 UTC
Labels: Bug

**Comment by vpagini** [comment] 2024-04-09 21:10
@MajorTanya so sorry about the duplicate, it was my first time opening an issue on github and I don't have a Discord account!
Thanks to everyone for the suggestions though :)

**Comment by MajorTanya** [comment] 2024-04-09 21:16
> @MajorTanya so sorry about the duplicate, it was my first time opening an issue on github and I don't have a Discord account!
> Thanks to everyone for the suggestions though :)

This should be fixed now in the newest update of Mihon (0.16.5). Please see if that fixed the crash loop for you.
