### ISSUE TITLE
Update Preference List or View

### ISSUE THREAD

**Issue by shirruy** [mihonapp/mihon#135] opened 2024-01-19 09:50 UTC
### Describe your suggested feature

Hi Devs ,

Hope you are dong well, any ways I wanted to raise a request if possible that we can add somewhere in the update tab a way to have a filter to stack all the incoming update and not just per chapter just like what we have in Tachi2JK.

Thank you for all your hard work and more power
![Uploading Screenshot_2024-01-19-17-28-40-509_eu.kanade.tachiyomi.j2k.jpg…]()

### Other details

Hi Devs ,

Hope you are dong well, any ways I wanted to raise a request if possible that we can add somewhere in the update tab a way to have a filter to stack all the incoming update and not just per chapter just like what we have in Tachi2JK.

Thank you for all your hard work and more power
![Uploading Screenshot_2024-01-19-17-28-40-509_eu.kanade.tachiyomi.j2k.jpg…]()

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2024-01-21 12:47
Duplicate of #44

**Closed by AntsyLich** 2024-01-21 12:47 UTC
Labels: Feature request
