### ISSUE TITLE
Updating extensions problem

### ISSUE THREAD

**Issue by Mingo3347** [mihonapp/mihon#181] opened 2024-01-21 21:53 UTC
### Steps to reproduce

Trying to update an extension, after hitting install and it keep downloading for like 8 seconds and then it just doesn't disappear from the updating extensions list 

### Expected behavior

The extension should disappear after installing it 

### Actual behavior

It doesn't disappear from the extensions updating list

### Mihon version

0.16.1

### Android version

Android 11

### Device

Samsung a70 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment] 2024-01-21 21:58
Please check other issues before opening another, there several duplicates of this already from a cursory search

**Comment by AntsyLich** [comment] 2024-01-22 02:29
Duplicate of #179

**Closed by AntsyLich** 2024-01-22 02:29 UTC
Labels: Bug
