### ISSUE TITLE
Kitsu tracker failed to bypass CloudFlare

### ISSUE THREAD

**Issue by cuong-tran** [mihonapp/mihon#1359] opened 2024-10-23 09:40 UTC
### Steps to reproduce

- Try log in to Kitsu tracker
- Or if already logged in then try to open Kitsu tracker from entry's page

### Expected behavior

- Should be able to log in
- Should be able to search Kitsu tracker or update tracker

### Actual behavior

Show toast saying "Failed to bypass CloudFlare"

### Mihon version

latest dev build

### Android version

Android 14

### Device

AVD

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment] 2024-10-23 09:57
Cannot reproduce, neither on a fresh beta install nor on my daily driver instance. Are you sure it's Kitsu throwing this error? I know AniList tracking throws this whenever AniList is in maintenance mode.

**Comment by cuong-tran** [comment] 2024-10-23 10:28
CloudFlare might only require to bypass on some network. It happens on all of my Wi-Fi or mobile network. That means they started to use CloudFlare.

<img width="1287" alt="image" src="https://github.com/user-attachments/assets/83a81f04-245e-4f2c-8c64-a11ab4b27006">

**Comment by MajorTanya** [comment] 2024-10-23 10:40
> CloudFlare might only require to bypass on some network. It happens on all of my Wi-Fi or mobile network. That means they started to use CloudFlare.
> 
> <img width="1287" alt="image" src="https://github.com/user-attachments/assets/83a81f04-245e-4f2c-8c64-a11ab4b27006">
> 

I've tried using a VPN to various locations around the world, including but not limited to Vietnam, Philippines, USA, and Brazil. I've used a clean install incognito browser and I've freshly connected Kitsu through Mihon's newest beta release.

Not only did I not see any Cloudflare page like you showed, it still worked fine in Mihon.

Obviously they are using Cloudflare but Kitsu may have just increased their protection level and that's somehow causing you and some others to get sent the challenge page. I don't know why this would be happening but it is.

I'd suggest trying a different User-Agent string, similar to how the MAL bypass works, but that's just an unfounded idea.

Do you happen to have a screenshot of the toast, or better yet, a stack trace/log entry for when this happens?

**Comment by cuong-tran** [comment] 2024-10-23 11:17
Screenshot on Mihon latest beta

![image](https://github.com/user-attachments/assets/76e44159-0b64-4d1f-b439-780250eb3419)

Logcat only shows this:
```
2024-10-23 18:17:16.921  4913-4913  chromium                app.mihon.debug                      I  [INFO:CONSOLE(0)] "Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'browsing-topics'.", source:  (0)
2024-10-23 18:17:16.921  4913-4913  chromium                app.mihon.debug                      I  [INFO:CONSOLE(0)] "Error with Permissions-Policy header: Unrecognized feature: 'hid'.", source:  (0)
2024-10-23 18:17:16.921  4913-4913  chromium                app.mihon.debug                      I  [INFO:CONSOLE(0)] "Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.", source:  (0)
2024-10-23 18:17:16.921  4913-4913  chromium                app.mihon.debug                      I  [INFO:CONSOLE(0)] "Error with Permissions-Policy header: Unrecognized feature: 'payment'.", source:  (0)
2024-10-23 18:17:16.921  4913-4913  chromium                app.mihon.debug                      I  [INFO:CONSOLE(0)] "Error with Permissions-Policy header: Unrecognized feature: 'serial'.", source:  (0)
2024-10-23 18:17:16.921  4913-4913  chromium                app.mihon.debug                      I  [INFO:CONSOLE(0)] "Error with Permissions-Policy header: Unrecognized feature: 'usb'.", source:  (0)
```

**Comment by MajorTanya** [comment] 2024-10-23 13:32
I see. Presumably it happens with proper credentials too.

I tried again just now and it acted normally still on my end. I'll keep the issue open but it's difficult to debug something one doesn't see - maybe someone will eventually get this themselves and can then figure out what's going on.

**Comment by jenice11** [comment] 2024-10-24 09:16
In thr latest preview build r567,
As of now I had tried:

- changing default user agent string
- changing network, dns 
- using webview to access kitsu.app to prompt cloudflare ends up stuck in loop after verifying (i went to webtoon, google play store, google privacy, google search, kitsu)
- clearing cookies and webview data

> on a side quest, i went to tachij2k to login kitsu no problem haha

Still receiving cloudflare error upon login kitsu

**Comment by MajorTanya** [comment] 2024-10-26 02:04
Update: I have contacted Kitsu about this and they told me that they activated Cloudflare protection for some countries due to heavy spam. They will however tweak the settings of this protection so it doesn't affect the API. No concrete ETA was given.

If I get told the restriction on the API was lifted, or if some affected user(s) report that their Kitsu tracking works again, I'll update here again and hopefully I'll be able to close the issue. 👍

**Comment by prem12321kumar** [comment] 2024-10-26 20:50
Just update the app and this cloudflare issue got me too. 😓
So,  no solution as of now?

**Comment by MajorTanya** [comment] 2024-10-26 20:53
> Just update the app and this cloudflare issue got me too. 😓 So, no solution as of now?

What Mihon version you're using doesn't matter for this, as it is a measure on Kitsu's end. Wait for Kitsu to drop the limitations on the API and it'll work again, no need for a new Mihon version when that happens.

**Comment by MajorTanya** [comment] 2024-10-27 21:45
@cuong-tran @jenice11 @prem12321kumar Kitsu has told me they applied a fix, do any of you still experience this issue when trying to use Kitsu through Mihon?
Notably, the _website_ will still have Cloudflare protection so that may be unchanged for you. However, interacting with its API should be working normally again.

**Comment by cuong-tran** [comment] 2024-10-28 01:57
Mihon stable 1.7.0 is working.
Mihon preview r6954, r6971 (latest) is still not, why though?

**Comment by BrutuZ** [comment] 2024-10-28 01:59
Different user-agents? :thinkies:

**Comment by MajorTanya** [comment] 2024-10-28 02:00
> Mihon stable 1.7.0 is working. Mihon preview r6954, r6971 (latest) is still not, why though?

Could you try force closing the previews, emptying their cache (Not App Data(!)), and checking again? This should be a purely Kitsu-side fix and Mihon shouldn't have to do anything about this. @cuong-tran

**Comment by cuong-tran** [comment] 2024-10-28 02:06
replaced preview ver's user-agent with stable's user-agent, still failed.
Clear App Data on preview ver still failed.

**Comment by MajorTanya** [comment] 2024-10-28 02:10
> replaced preview ver's user-agent with stable's user-agent, still failed. Clear App Data on preview ver still failed.

I'm pretty sure newest preview and current stable have the same UAs anyway since there haven't been any commits to main in the meantime. If possible, could you try to reinstall those previews for a proper clean slate or w/e?

**Comment by cuong-tran** [comment] 2024-10-28 02:10
correction:
Mihon stable 0.16.5 - working
Mihon stable 0.17.0 - not working
Mihon preview r6954, r6971 (latest) - not working

Guess it's another issue with Tracker client then.

**Comment by MajorTanya** [comment] 2024-10-28 02:13
What about logging out of Kitsu and logging back in on the "not working" versions?

**Comment by cuong-tran** [comment] 2024-10-28 02:16
> What about logging out of Kitsu and logging back in on the "not working" versions?

Those not-working version haven’t able to logged in yet, fresh install.
Mihon stable 0.16.5: tried login/log out several times - all works.

**Comment by cuong-tran** [comment] 2024-10-28 02:20
> That makes even less sense though... Again, this has nothing to do with changes Mihon has made to its handling of Kitsu, just Kitsu throwing up a Cloudflare challenge on their API and tweaking that now.
Maybe the new API Mihon using still got blocked.

**Comment by MajorTanya** [comment] 2024-10-28 02:27
Mihon hasn't changed what API it is using for Kitsu either. I'll talk to the folks at Kitsu some more, maybe we can figure out what's going on. I'll update again when I hear back.

**Comment by MajorTanya** [comment] 2024-10-28 03:15
@cuong-tran please try again now 👍 Should Just Work™

**Comment by cuong-tran** [comment] 2024-10-28 03:18
working!

**Comment by MajorTanya** [comment] 2024-10-28 03:19
> working!

on all the different versions? Previews, old and new stable, etc?

**Comment by cuong-tran** [comment] 2024-10-28 03:22
Stable 0.17.0 & Preview r6971 (latest) is working. Don't have time to tested older version yet.
Both login & tracking works.

**Comment by MajorTanya** [comment] 2024-10-28 03:25
Amazing 🚀 Closing this issue as solved then. 👍 Thanks for the report and patience of everyone who had to deal with this.

**Closed by MajorTanya** 2024-10-28 03:25 UTC
Labels: Bug

**Comment by prem12321kumar** [comment] 2024-10-28 06:20
> @cuong-tran @jenice11 @prem12321kumar Kitsu has told me they applied a fix, do any of you still experience this issue when trying to use Kitsu through Mihon? Notably, the _website_ will still have Cloudflare protection in your browsers so that may be unchanged for you. However, interacting with its API should be working normally again.

Yep, thanks

**Comment by jenice11** [comment] 2024-10-28 06:29
> @cuong-tran @jenice11 @prem12321kumar Kitsu has told me they applied a fix, do any of you still experience this issue when trying to use Kitsu through Mihon? Notably, the _website_ will still have Cloudflare protection in your browsers so that may be unchanged for you. However, interacting with its API should be working normally again.

Yeap its working for me too now.
