### ISSUE TITLE
widget not loading

### ISSUE THREAD

**Issue by Serrenos** [mihonapp/mihon#1360] opened 2024-10-23 13:08 UTC
### Steps to reproduce

add widget to home screen

### Expected behavior

the widget should show recent updates on favorites
![Screenshot_20241023_092623_One UI Home](https://github.com/user-attachments/assets/32f894cd-48d7-4eed-b926-4650a65f3c14)

### Actual behavior

the widget doesn't load
![Screenshot_20241023_093330_One UI Home](https://github.com/user-attachments/assets/292e52b7-a49e-4196-85f0-c4153459bc53)

### Mihon version

App version: 0.16.5 (standard, 2a01a2a, 6, 2024-04-09T09:58:14Z) Android version: 14 (SDK 34; build UP1A.231005.007.X610XXU5BXHB) 

### Android version

Android 14 (SDK 34; build UP1A.231005.007.X610XXU5BXHB) 

### Device

 SAMSUNG GALAXY TAB S9 FE+ Device model: SM-X610

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-10-23 18:11
Duplicate of #491

Maybe you need new unread chapters in your Updates tab (as mentioned in the issue above), or from my quick testing back then, adjusting the sizing for the widget might refresh/load up the results.

**Closed** 2024-10-23 18:11 UTC
Labels: Bug
