### ISSUE TITLE
Unable to update extension

### ISSUE THREAD

**Issue by Himx18** [mihonapp/mihon#759] opened 2024-05-04 10:50 UTC
### Steps to reproduce

I'll add screenshot of the issue here 
![Screenshot_20240504-160132_Mihon](https://github.com/mihonapp/mihon/assets/167764463/b869cf8d-01e6-44f1-b7d6-e354a3b600a7)
![Screenshot_20240504-160140_Package installer](https://github.com/mihonapp/mihon/assets/167764463/10c44704-924a-41b6-9feb-ee042c53e0db)
![Screenshot_20240504-160146_Mihon](https://github.com/mihonapp/mihon/assets/167764463/28a8efcb-2a1f-4389-a8e5-5b11c89b2f29)

The first screenshot is before the update.
Second screenshot is while updating 
And the last is AFTER updating it 
I'll add another screenshot after doing this so check the time and the total extension count 
![Screenshot_20240504-161004_Mihon](https://github.com/mihonapp/mihon/assets/167764463/5ba087dc-70e1-43ab-9941-aa483c875e76)

It's happening to me for months now 

### Expected behavior

.

### Actual behavior

.

### Crash logs

.

### Mihon version

Stable 0.16.5

### Android version

Android 12

### Device

Samsung F41

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2024-05-04 10:52
Duplicate of #496

**Closed by AntsyLich** 2024-05-04 10:52 UTC
Labels: Bug
