### ISSUE TITLE
Mass migration 

### ISSUE THREAD

**Issue by Ventus4469** [mihonapp/mihon#61] opened 2024-01-17 01:22 UTC
### Describe your suggested feature

I know an old fork had the ability to migrate multiple mangas instead of 1 at a time which can be timeconsuming.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by TheColorman** [comment] 2024-01-17 12:24
If you export a backup from Tachi and import it into Mihon entries should also be migrated automatically.

**Comment by AntsyLich** [comment] 2024-01-17 12:27
The feature is about mass migration between sources

**Comment by TheColorman** [comment] 2024-01-17 12:28
Ah sorry, misunderstood as app migration, my bad.

**Comment by DatHypnoboi** [comment] 2024-01-26 08:00
If you're referring to TachiyomiSY, it's still actively being developed, so as a sketchy workaround you could restore your library to SY, mass migrate, and then restore back to Mihon, still probably less work than migrating 1 by 1

**Comment by WybeBosch** [comment] 2024-03-10 08:56
Im wondering about this feature aswell, is there a way to migrate from one "extension repo" to another extension repo?
I know you can migrate individual manga between "source extensions" but doing that by hand would take forever.

**Comment by AntsyLich** [comment] 2024-05-05 10:20
Duplicate of #14

**Closed by AntsyLich** 2024-05-05 10:20 UTC
Labels: Feature request
