### ISSUE TITLE
Swipe Back doesnt Have Animation

### ISSUE THREAD

**Issue by kazuhachuli** [mihonapp/mihon#34] opened 2024-01-16 14:36 UTC
### Steps to reproduce

1.- Open Mihon 
2.- You are at library
3.- Swipe back with gesture(right to left or left to right) to go at Home (Android Desktop)
4.- When i swipe back the animation doesnt appear

### Expected behavior

There should be an animation when you swipe back to go home.

### Actual behavior

There is no animation when there should be

### Mihon version

0.16.0

### Android version

Android 13

### Device

Poco X3 Pro MIUI 14

### Other details

In Tachiyomi 0.14.7 this error doesnt occur but in 0.15 yes
When you swipe from bottom to top the animation works only doesnt appear when you swipe right to left or left to right

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.15.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [x] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Xori71** [comment] 2024-01-16 16:03
Not an app issue. Works fine for me.

**Comment by kazuhachuli** [comment] 2024-01-16 16:06
For some devices works fine, I don't understand why it doesn't work, for Tachiyomi 0.14.7 works fine but after code refactoring at Tachiyomi 0.15.0 doesnt work :(

**Comment by kazuhachuli** [comment] 2024-01-16 16:13
Device: M2102J20SG
Android ver: 13
MIUI ver: 14
Idk what is Android skin, if it means custom rom, i dont have custom rom

**Comment by Xori71** [comment] 2024-01-16 16:14
> Device: M2102J20SG Android ver: 13 MIUI ver: 14 Idk what is Android skin, if it means custom rom, i dont have custom rom

An Android skin is software running on top of AOSP that OEMs implement on their devices. MIUI, which you seem to have, is one of them.

**Comment by kazuhachuli** [comment] 2024-01-16 16:18
Then i have MIUI, I specified that in my first message.
It's exasperating that this happens to me honestly, possibly it was because of the refactoring code at 0.15.0

**Comment by Xori71** [comment] 2024-01-16 16:19
Check the preview build of Mihon to see if the issue is still present or
not.

**Comment by kazuhachuli** [comment] 2024-01-16 16:35
Not work at Mihon Preview r6442

**Comment by Xori71** [comment] 2024-01-16 17:36
> Okie :) thank you

No problem.

**Comment by OmarShezan** [comment] 2024-01-18 12:33
Works find on my device 
Samsung S9
Android 10
One UI version 2.5

@kazuhachuli make sure in developer mode you haven't turned off animation also check if animation works on other apps. it'll be helpful if you can screen record your issue and attach it here

**Comment by kazuhachuli** [comment] 2024-01-18 19:47
Animations are activated, it is an app problem, when you swipe from bottom to top the animation works only doesnt appear when you swipe right to left or left to right

**Comment by theolm** [comment] 2024-01-29 00:53
@kazuhachuli could you provide a video of the issue? It seems to work fine here.

**Comment by kazuhachuli** [comment] 2024-01-29 08:22
> @kazuhachuli could you provide a video of the issue? It seems to work fine here.


https://github.com/mihonapp/mihon/assets/59351873/c00e64a4-cc1f-42b1-ae69-51a47819585f

**Comment by FooIbar** [comment] 2024-01-30 08:54
It's a known issue with predictive back on Android 13-based MIUI.
One solution is to disable predictive back on Android 13.

**Comment by kazuhachuli** [comment] 2024-01-30 09:39
I dont have predictive back activated at developer options, its disabled. Also in other apps works fine

**Comment by FooIbar** [comment] 2024-01-30 09:42
> I dont have predictive back activated at developer options, its disabled. Also in other apps works fine

That's the problem.
It's broken even with predictive back disabled in developer options if the app has `enableOnBackInvokedCallback=true`.

**Comment by kazuhachuli** [comment] 2024-01-30 12:40
How can i disable on app side?

**Comment by kazuhachuli** [comment] 2024-01-30 12:42
Oh well, I think you mean the developers change it, patience and wait i think

**Comment by AntsyLich** [comment] 2024-01-31 11:25
Won't fix. Rational: https://github.com/mihonapp/mihon/pull/288#issuecomment-1918915444

**Closed by AntsyLich** 2024-01-31 11:25 UTC
Labels: Bug
