### ISSUE TITLE
Scroll to previous chapter not working when zoomed out

### ISSUE THREAD

**Issue by F-shark** [mihonapp/mihon#1462] opened 2024-11-09 10:55 UTC
### Steps to reproduce

When I zoom out and scroll to the next chapter, whenever I try to scroll to the previous chapter it doesn't let me (I read zoomed out on my tablet)  instead I have to zoom to the normal size to scroll back to the previous chapter so this is really annoying, please fix
See here:
https://github.com/user-attachments/assets/58307094-2c36-4a6b-a27b-a6af3339bd39

### Expected behavior

I should be able to scroll back to the next chapter while zoomed out

### Actual behavior

Please fix this

### Mihon version

0.17.0

### Android version

Android 11

### Device

Lenovo TB-J616F tablet

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-11-09 13:21
Duplicate of #1346 (as you so mentioned yourself there)

**Closed by Smol-Ame** 2024-11-09 13:21 UTC
Labels: Bug
