### ISSUE TITLE
Library Sync with Multiple device

### ISSUE THREAD

**Issue by MaouGoku** [mihonapp/mihon#1451] opened 2024-11-06 17:08 UTC
### Describe your suggested feature

I use three device to read mangas. But while adding a new series in library is hassle as i have to manually add in every device. I had thought of using back and restore but its also problematic as none of the device are main (i randomly add series in whichever device i have near). So creating a feature which would link the libraries would be good
(maybe some feature like acc or token would be connected to gdrive where every connected device notes its changes in a log file which the app retrieves at frequency specified by user)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment] 2024-11-06 17:13
> - [X] I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open or closed issue.

LIES!!!
Duplicate of #812 #1432 ... Something something #40

**Closed** 2024-11-06 18:17 UTC
Labels: Feature request
