### ISSUE TITLE
Simple Migration

### ISSUE THREAD

**Issue by SaturnsVoid** [mihonapp/mihon#1160] opened 2024-08-25 19:27 UTC
### Describe your suggested feature

So i have lots of dead comics, manga, etc due to the sites being shutdown, blocking or the extension being abandoned. The current migration method works but it takes a while. It would be nice if there was a kinda one click option that would search for the names of all the series under one extension and search through all the others, check if chapters are available and not missing any then auto migrate to them.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-08-25 19:56
Duplicate of #14 

Personal take, but auto-migrate would be a mess. More chapters doesn't equal all chapters, different sites have different naming schemes & how they divvy up things. Plus, there's similar titles, alternative titles, etc etc, so auto-migrating to something might just put your Library into disarray

**Closed by Smol-Ame** 2024-08-25 19:56 UTC
Labels: Feature request
