### ISSUE TITLE
View full reading history (all chapters)

### ISSUE THREAD

**Issue by Archimedes9500** [mihonapp/mihon#1139] opened 2024-08-20 01:06 UTC
### Describe your suggested feature

Currently History tab shows only the date of the most recently touched chapter from each series, even though the app has data about every chapter.

It should be possible to view this information from within the app rather than only thorugh external tools or by deleting most recently read chapter from history.

### Other details

Possible implementations within History tab:

- Add `History\Show/Hide all chapters` toggle option next to `History\Remove everything` option

- Replace `History\Remove everything` option with `History\Overflow` option and then add a `Show/Hide all chapters` toggle option there

- Replace `History entry\Delete` option with `History entry\Overflow` option that would contain a `Show all chapters` option, which would open a screen with  read history of all chapters from only that title

- Add `History entry\Hold` action that would activate the option for that entry

Possibly this data could also be visible in Chapters view as mentioned [here](https://github.com/mihonapp/mihon/issues/1123#issuecomment-2290015237)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment] 2024-08-20 01:34
> calling it "objectively wrong" seems a bit far out 

Taking that seriously is what "seems far out". It was clearly a joke, there was even a freaking emoji! щ(゜ロ゜щ)

**Comment by TimoNotThy** [comment] 2024-08-20 09:34
I suggest closing this issue to not have duplicates

**Comment by Smol-Ame** [comment] 2024-08-20 23:39
Closing as a duplicate of #1123 (since they clarified what they wanted in the comments)

**Closed by Smol-Ame** 2024-08-20 23:39 UTC
Labels: Feature request
