### ISSUE TITLE
Ghost Touch

### ISSUE THREAD

**Issue by ViewtifulDave** [mihonapp/mihon#547] opened 2024-03-20 06:17 UTC
### Steps to reproduce

Go to any series and try to select multiple chapters

### Expected behavior

I select more than 1 chapter

### Actual behavior

I keep selecting the wrong chapter.its like the ghost touch is on the previous touch, meaning if I were to select chapter 1 then select chapter 2, I end up deselecting 1

### Mihon version

0.16.4

### Android version

Fire OS 8 (a variant of Android 11]

### Device

Kindle Fire Max 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Yutasj** [comment] 2024-03-20 12:33
@ViewtifulDave There may be a problem with your display, I don't have such a problem

**Comment by Wylie03** [comment] 2024-03-20 22:21
I just got a Fire HD 10 (2023 version) today and I'm having this issue as well. I don't have this issue on my Fire HD 8 Plus (2020 Version) though. Whenever I use the Playstore on my HD 10 I also have this issue, specifically when I search something, install the app, then try to search for another app. It will repeat the last touch so instead of me searching again it cancels the installation. Can you check yours and see if you have this issue as well? It is possible that we both got bad screens. It is far worse on Mihon though, genuinely unusable. I'm unable to do anything because I keep getting ghost touches.

**Comment by Smol-Ame** [comment] 2024-08-19 10:35
Closing as a duplicate of #70

This seems to be an issue with Amazon tablets, and seems to have fixed itself in Mihon Preview with a Compose update. Wait for a future Mihon Stable update or try out Mihon Preview for now.

**Closed by Smol-Ame** 2024-08-19 10:35 UTC
Labels: Bug
