### ISSUE TITLE
Manhwa not loading 

### ISSUE THREAD

**Issue by Lushan-svg** [mihonapp/mihon#1461] opened 2024-11-09 10:24 UTC
### Steps to reproduce

Not all my manhwa are loding it was fine before the 17 th update I truly love this app so I humbly request the you plz help solve this issue 
![Screenshot_20241109-162116_Mihon](https://github.com/user-attachments/assets/1810bca2-c8e4-47a2-a9c5-329cab859ace)
![Screenshot_20241109-162113_Mihon](https://github.com/user-attachments/assets/109a0555-879f-4626-9b53-90e71157ae0c)
![Screenshot_20241109-162104_Mihon](https://github.com/user-attachments/assets/c45d3b7b-76c6-411b-8ecb-a34125c8e496)

### Expected behavior

This happens in only in manhwa not manga

### Actual behavior

This happens after update 0.17.0

### Crash logs

content://app.mihon.provider/ext_cache_files/mihon_crash_logs.txt

### Mihon version

0.17.0

### Android version

Android 8

### Device

Samsung Galaxy j7 prime 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-11-09 10:27
Duplicate of #1436

Search the existing issues first before opening a new one, and acknowledging that you did when you didn't. Also come to the Mihon Discord support channel for quick troubleshooting/potential workaround for this issue.

**Closed by Smol-Ame** 2024-11-09 10:27 UTC
Labels: Bug
