### ISSUE TITLE
Myanimelist tracking not working

### ISSUE THREAD

**Issue by NKJibu02** [mihonapp/mihon#350] opened 2024-02-05 22:15 UTC
### Steps to reproduce

Clicked on the tracking button, entered myanimelist and found the tracking showing unknown error. Tried other mangas i tracked using myanimelist but none refuse to update

### Expected behavior

Mana
Gas should have been updated but not working and new entries should show but not working. 

### Actual behavior

Shows unknown error everytime

### Mihon version

0.16.3

### Android version

Android 10 

### Device

Infinix SMART 6/X657C 

### Other details

Please rectify the issue

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment] 2024-02-05 22:17
Duplicate of #298. Please at least search through the existing issues before opening a new one, thank you.

**Closed by MajorTanya** 2024-02-05 22:17 UTC
Labels: Bug
