### ISSUE TITLE
Updating extensions

### ISSUE THREAD

**Issue by MaksNPC** [mihonapp/mihon#455] opened 2024-02-26 13:39 UTC
### Steps to reproduce

After updating an already installed extension, confirmation of the reliability of the extension is required.

https://github.com/mihonapp/mihon/assets/55586822/15641fdc-eea3-408f-a032-7295094cc8d2

### Expected behavior

The extension should have been updated without the need to re-confirm the reliability of the extension

### Actual behavior

After an update, an already installed extension asks for re-confirmation of the extension’s reliability

### Mihon version

0.16.3

### Android version

Android 14

### Device

Redmi Note 8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment] 2024-02-26 15:20
This is by design. There are some plans to change how trusting extensions works but right now, that's working as intended. Code of extensions might have changed, so it is up to the user to re-accept the risks by trusting the extensions.
Closing as won't fix.

**Closed by MajorTanya** 2024-02-26 15:20 UTC
Labels: Bug
