### ISSUE TITLE
Add undo button when removing entries

### ISSUE THREAD

**Issue by isabella-almeidaa** [mihonapp/mihon#1153] opened 2024-08-24 16:39 UTC
### Describe your suggested feature

J2k has this feature.
Is a message that appears on the bottom of the screen with an undo button after removing entries

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment] 2024-08-24 17:10
But why? There's already a 2-step confirmation dialog to delete an entry

**Comment by isabella-almeidaa** [comment] 2024-08-24 17:21
> But why? There's already a 2-step confirmation dialog to delete an entry

that only happens if you're in the library, not in the entry itself
if you missclicked it on the entry, it would just remove it right away

**Comment by BrutuZ** [comment] 2024-08-24 17:23
Tap again and add it back?

**Comment by isabella-almeidaa** [comment] 2024-08-24 17:25
> Tap again and add it back?

it wouldn't have the previous categories
if you have  a lot of them, its a pain to add them back but I would understand if this isn't enough to add this as a feature
also, in j2k it stays there for a long time so rushing to it wouldn't be the case

**Comment by Smol-Ame** [comment] 2024-08-24 17:30
It does keep it

https://github.com/user-attachments/assets/6c287ec1-9ac5-46ed-96c2-3d60cbfec147

**Comment by Smol-Ame** [comment] 2024-08-24 17:31
Also, since you clarified, duplicate of #391

**Closed by Smol-Ame** 2024-08-24 17:31 UTC
Labels: Feature request
