### ISSUE TITLE
Wrong date in history

### ISSUE THREAD

**Issue by joaoandre120** [mihonapp/mihon#204] opened 2024-01-23 01:20 UTC
### Steps to reproduce

1. Read a couple of different manga.
2. Open history list.
3. It's gonna show the wrong date (today, yesterday...).

### Expected behavior

Show the right date

### Actual behavior

Showing the wrong date

![3](https://github.com/mihonapp/mihon/assets/7441934/451770ab-e631-4329-bde0-58229b9beff4)

### Mihon version

0.16.1

### Android version

Android version: 10 (SDK 29)

### Device

UMIDIGI A9 Pro

### Other details

It started with the last version of tachi.

![1](https://github.com/mihonapp/mihon/assets/7441934/febbdb7d-91f8-4603-bc8c-f60172708c82)
![2](https://github.com/mihonapp/mihon/assets/7441934/98bca905-4e06-4b02-ad57-713cfd52d7f8)
![3](https://github.com/mihonapp/mihon/assets/7441934/451770ab-e631-4329-bde0-58229b9beff4)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by dthunes** [comment] 2024-01-23 03:31
I have the same issue. It also appears on the Updates tab. I think it has to do with the GMT offset. My offset is -6 and interestingly, the error doesn't occur at night.

**Comment by joaoandre120** [comment] 2024-01-23 21:58
On Updates tab I didn't realize, and my timezone is -3, if it helps.

**Comment by dthunes** [comment] 2024-01-24 23:53
To be clear, the time shows correctly, it just incorrectly groups things as yesterday. It will also move things that are correctly labeled as "Today" to yesterday, but I'm not sure how to replicate that behavior.

joaoandre120's screenshot proves the "yesterday" and "today" lables are (incorrectly) based on GMT and the time is (correctly) based on local timezone. Their timezone is -3 and everything before 21:00 is yesterday and everything after 21:00 is today.

**Comment by dragon-masterk** [comment] 2024-02-13 17:12
I'm seeing the same behavior in the Updates tab: 
![Screenshot_20240213_120019](https://github.com/mihonapp/mihon/assets/83424830/76dbd0d9-1c89-46f8-a22a-d7372d88351a)
![Screenshot_20240213-115919_Mihon](https://github.com/mihonapp/mihon/assets/83424830/c48c5f9b-b378-415f-a546-a7c2d2bd0b8a)

My timezone offset is -5. 

I tried changing my timezone to UTC and looking at the Update Tab again. The date is correct:
![Screenshot_20240213-171010_Mihon](https://github.com/mihonapp/mihon/assets/83424830/b041d13b-eb42-42e7-8ef2-ea52d29367b1)

So it must just not be implementing the timezone shift correctly.

**Comment by dragon-masterk** [comment] 2024-02-13 17:18
Also seems like this was tagged before as an issue #58

**Comment by MajorTanya** [comment] 2024-02-15 00:32
Yeah, this looks to me like a duplicate of #58, closing as such.

**Closed by MajorTanya** 2024-02-15 00:32 UTC
Labels: Bug
