### ISSUE TITLE
Mihon Crashes When Migrating/Deleting Series

### ISSUE THREAD

**Issue by Firestorm808** [mihonapp/mihon#313] opened 2024-02-01 11:28 UTC
### Steps to reproduce

I'm currently trying to consolidate my series to reduce entries. 
1. Have Series 1 saved to library from Extension 1
2. Have Series 1 saved to library from Extension 2
3. Migrate Series 1 from Extension 1 to Extension 2
4. Mihon has an error and Crashes

### Expected behavior

I am expecting the series to consolidate in the target Extension 2.

### Actual behavior

The series does consolidate in Extension 2, but it causes the app to crash.

### Crash logs

[mihon_crash_logs.txt](https://github.com/mihonapp/mihon/files/14124540/mihon_crash_logs.txt)

### Mihon version

r6499

### Android version

Android 13

### Device

Samsung Galaxy S20

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by samanta-widjaja** [comment] 2024-02-02 02:35
the crash come from delete series from extension 1. it also happened when you just delete the series. please fix this

**Comment by Firestorm808** [comment] 2024-02-02 02:58
> the crash come from delete series from extension 1. it also happened when you just delete the series. please fix this

I have also experienced this when just removing a series from my library, but I forgot to save the crash log for it.

**Comment by THElegend5** [comment] 2024-02-02 04:02
Duplicate of #93

**Closed** 2024-08-14 21:13 UTC
Labels: Bug
