### ISSUE TITLE
"The image couldn't be loaded" error when reading downloaded chapters

### ISSUE THREAD

**Issue by IDontKnow218** [mihonapp/mihon#379] opened 2024-02-11 03:53 UTC
### Steps to reproduce

1. Download a chapter
2. Load it
3. "The image couldn't be loaded" error appears

### Expected behavior

Downloaded chapter can be read normally 

### Actual behavior

"The image couldn't be loaded" error shows up

### Mihon version

Beta r6505

### Android version

Android 9

### Device

Samsung Galaxy Note 8

### Other details

The problem was also in Beta r6501.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by ridho9** [comment] 2024-03-08 02:19
I'm also experiencing this issue, the last build that doesn't have problem for me is r6499

**Comment by IDontKnow218** [comment] 2024-03-08 10:24
> I'm also experiencing this issue, the last build that doesn't have problem for me is r6499

You're right. It seems they did some changes to the downloaded chapters in the version after r6499 and broke something.

**Comment by Smol-Ame** [comment] 2024-08-19 10:35
Closing as a duplicate of #63

If you are still experiencing issues, read latest comment on that issue request.

**Closed by Smol-Ame** 2024-08-19 10:35 UTC
Labels: Bug
