### ISSUE TITLE
When I download 40 chapter or more it start to become slow

### ISSUE THREAD

**Issue by ZoMpziO** [mihonapp/mihon#723] opened 2024-04-28 22:42 UTC
### Steps to reproduce

I'm reading Martial Peak and have a lot of chapters and when I start downloading about 100 chapter it took about 5 minutes to just start downloading and the number of time is increasing the more chapters i download and when it start downloading the app start to lag 

### Expected behavior

Run normally

### Actual behavior

 the app start to lag

### Crash logs

[mihon_crash_logs.txt](https://github.com/mihonapp/mihon/files/15144111/mihon_crash_logs.txt)

### Mihon version

App version: 0.16.5

### Android version

Android 10

### Device

Huawei y7p

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment] 2024-04-28 23:13
This issue description reads like that old joke:
> Patient wake into doctor's office 
> \- Patient: Hey doc, it hurts when I do this *\*stabs himself\**
> \- Doctor: Then don't do it

**Comment by FooIbar** [comment] 2024-04-29 05:08
It sounds similar to #705

**Comment by raxod502** [comment] 2024-04-30 02:11
> The app doesn't start to lag, the extension is rate limiting to save you from your naive self. It is slowing down so you won't get banned from the source and then you won't be able to read your manhwa at all. There is a reason the app gives you a warning when downloading large amounts.

This is false, and inappropriately blames the user for what is actually a bug in the software. Please see https://github.com/mihonapp/mihon/issues/705 for a technical analysis of what is really going on.

**Comment by raxod502** [comment] 2024-04-30 03:21
We may be able to close this as a duplicate of https://github.com/mihonapp/mihon/issues/705, since I believe the reported problem (that UI performance suffers when initiating downloads) is the same. The original poster can correct me if I've misunderstood their report.

Of course, nobody expects that _downloading_ a large number of chapters should be fast, because appropriate rate limiting should be applied in order to avoid placing unacceptable load on upstream providers - and Mihon does indeed apply such rate limiting - but certainly adding a large number of chapters _to the download queue_ should be fast as it is a purely local operation, and certainly adding chapters to the download queue should not have run-on effects on device CPU utilization nor interface responsivity, as reported in https://github.com/mihonapp/mihon/issues/705#issuecomment-2079290042.

So, I think the only change that need be made here is to fix the filesystem performance degradation, and that is covered adequately in https://github.com/mihonapp/mihon/issues/705, hence my suggestion to close as duplicate.

**Comment by AntsyLich** [comment] 2024-05-04 10:46
Closing in favor of #705 which addresses the core issue

**Closed by AntsyLich** 2024-05-04 10:46 UTC
Labels: Bug
