### ISSUE TITLE
没有文件管理器 No file manager

### ISSUE THREAD

**Issue by zanjie1999** [mihonapp/mihon#1179] opened 2024-08-30 04:53 UTC
### Steps to reproduce

1.  安装打开应用   install app and open app
2. 选择文件夹       Select Folder
3. app提示”没有文件管理器“   App prompts "No file manager" 

### Expected behavior

使用安装的es文件管理器或是re管理器选择文件夹
Use the installed es file manager or re file manager to select the folder

### Actual behavior

<img width="634" alt="image" src="https://github.com/user-attachments/assets/3d8c1745-b465-4124-a24c-8bb485e1296e">

### Mihon version

0.16.5

### Android version

Android8

### Device

Magicpie M1

### Other details

this system no DocumentsUI

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-08-30 04:59
Are you emulating Android on a Mac to run Mihon?

If yes, I don't think we can help with any issues you are having. Otherwise, use a different emulator that has a File Manager/DocumentsUI, a core function of Android or something.

**Comment by zanjie1999** [comment] 2024-08-30 05:49
> Are you emulating Android on a Mac to run Mihon?
> 
> If yes, I don't think we can help with any issues you are having. Otherwise, use a different emulator that has a File Manager/DocumentsUI, a core function of Android or something.

No, just scrcpy, this elink pad does not have a screenshot function, so I projected the screen onto my mac and took a screenshot

**Comment by Smol-Ame** [comment] 2024-08-30 05:54
Ah okay, sorry, then I'm going to close this as a duplicate of closed #386 to follow the ruling in there.

You can try some of the workarounds mentioned in the comments section of the above issue to try and get Mihon working on your e-ink device, but it's not something we can support & just boils down to your device/OS lacking DocumentsUI.

**Closed by Smol-Ame** 2024-08-30 05:54 UTC
Labels: Bug
