### ISSUE TITLE
Paswords for categories

### ISSUE THREAD

**Issue by PedroGusta** [mihonapp/mihon#937] opened 2024-06-21 10:47 UTC
### Describe your suggested feature

When you go to some category, it'll ask you to enter your password, just like appblock does.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Animeboynz** [comment] 2024-06-21 13:21
> ### Acknowledgements
> * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.

Duplicate of #919 which is a duplicate of #349

**Closed** 2024-06-21 13:25 UTC
Labels: Feature request
