### ISSUE TITLE
Feature suggestion: background music support

### ISSUE THREAD

**Issue by raxod502** [mihonapp/mihon#1606] opened 2024-12-22 20:38 UTC
### Describe your suggested feature

Some sources provide music alongside a chapter. This is fairly common on Webtoons.com, for example. It'd be neat if the source API had support for optionally getting the URL of a music file that is intended to play alongside a chapter, and if Mihon had the option to play such tracks when they are returned.

### Other details

This was previously reported as a feature suggestion in https://github.com/mihonapp/mihon/issues/970, but the thread was immediately closed and locked with an offhand comment before any discussion could take place, which makes me unsure whether the appropriate level of consideration was given.

If a community member contributed the implementation, would a merge be considered?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.17.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment] 2024-12-22 20:44
Duplicate of #970

**Comment by AntsyLich** [comment] 2024-12-22 20:48
This has also been requested multiple before Mihon and all the time it was denied because the use case is very niche. As I said only 2 sites that I know of supports music playback and only one of them actively uses it (e.g. Webtoons)

From my personal point of view the current codebase especially the reader is a total mess and I don't want make it more messy. I'm slowly working on a rewrite (privately) and I may consider this when the rewrite is public so for now it's still a no

**Closed** 2024-12-22 20:48 UTC
Labels: Feature request

**Comment by AntsyLich** [comment] 2024-12-22 20:50
Also closed issues are automatically locked after 2 days of inactivity so they aren't necro'd

**Comment by AntsyLich** [comment] 2025-01-08 22:00
Feel free to start a discussion on https://github.com/mihonx/mihonx (extension API for the rewrite)
