### ISSUE TITLE
Add Collapsable Rows for Series in the Updates Tab

### ISSUE THREAD

**Issue by KenzKD** [mihonapp/mihon#171] opened 2024-01-21 09:45 UTC
### Describe your suggested feature

Certain series perform bulk updates periodically, leading to a congested and disorganized Updates Tab. 
Incorporating a drop-down menu could be beneficial in reducing clutter in the Updates Tab.

I am basing this off of the J2K implementation but I would like to change some things.

Change 1:

I believe that if the number of chapters in the past 24 hours or per day exceeds 3, the rows should be condensed into a single row with a drop-down button. However, if the count is 3 or fewer, it should remain as is. I find a drop-down for just 2 or 3 chapters to be more of a nuisance than a convenience.

Here is a example of the issue when there are only 2 chapters:

<img src="https://github.com/mihonapp/mihon/assets/65004578/b86af26a-351e-4aec-b24b-f4108654d280" width=50% height=50%>

Change 2:

I prefer the chapter display in the drop-down to keep the same sorting order as the rest of the Updates Tab. In J2K, the drop-down chapter display rearranges the order such that unread chapters are prioritized and sorted in ascending order by chapter number, while read chapters are deprioritized and sorted in descending order.

Here is a example of the issue: 

<img src="https://github.com/mihonapp/mihon/assets/65004578/fa1a7fc2-bc41-4d4b-87d2-00e105c6f8c7" width=50% height=50%>

Change 3:

I believe we should keep the earliest updated chapter visible in the collapsed row. However, upon expanding the drop-down, the initial row should only display the series title, with the drop-down chapter display, as mentioned in Change 2, appearing beneath it.

Kind of like this:

<img src="https://github.com/mihonapp/mihon/assets/65004578/f0efed35-f443-4eb5-a81f-7189260c7170" width=50% height=50%>

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2024-01-21 12:28
Duplicate of #44

**Closed by AntsyLich** 2024-01-21 12:28 UTC
Labels: Feature request
