### ISSUE TITLE
Mal not syncing 

### ISSUE THREAD

**Issue by ad3rsh** [mihonapp/mihon#311] opened 2024-02-01 02:38 UTC
### Steps to reproduce

After reading a chapter count in mal is updated.

### Expected behavior

Mal should update automatically without any errors.

### Actual behavior

When tried to manual update using the tracker button but it shows 403 and 503 error.

### Mihon version

0.16.3

### Android version

Android 14

### Device

Google pixel 6a

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment] 2024-02-01 02:52
Duplicate of #298, MAL is currently having API issues on their end and deactivated all manga endpoints.

**Closed** 2024-02-01 02:53 UTC
Labels: Bug
