### ISSUE TITLE
Drop down on same titled updates

### ISSUE THREAD

**Issue by lozerunite** [mihonapp/mihon#115] opened 2024-01-18 06:24 UTC
### Describe your suggested feature

Whenever there are new updates/chapters on manga/manhwa/manhua, it would be better if it was on a dropdown just like in the image below:
![Screenshot_20240118_142222_TachiyomiJ2K]
(Screenshot was taken from TachiyomiJ2K app)
(https://github.com/mihonapp/mihon/assets/54499179/dcff92ca-b079-44a4-9f98-efb372a18bae)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2024-01-18 07:33
Duplicate of #44

**Closed by AntsyLich** 2024-01-18 07:33 UTC
Labels: Feature request
