### ISSUE TITLE
Want to add a button to hide the "Missing 1930 chapters" prompt

### ISSUE THREAD

**Issue by JXing233** [mihonapp/mihon#600] opened 2024-03-30 12:43 UTC
### Describe your suggested feature

Want to add a button to hide the "Missing 1930 chapters" prompt
![0c03efb6e3c4754a1311899a3f6fcb2](https://github.com/mihonapp/mihon/assets/97931306/059b2d28-8799-4f7d-901a-4d24d685a4a5)
As shown in the picture, there is no missing chapter, but because there is another title between 82 and 83, it is judged that the chapter is missing. I hope that a button can be added to the settings to hide this prompt.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-08-19 10:35
Closing as a duplicate of #50

**Closed by Smol-Ame** 2024-08-19 10:35 UTC
Labels: Feature request
