### ISSUE TITLE
why does it say a manga is missing chapters when theyre not

### ISSUE THREAD

**Issue by 2fo2** [mihonapp/mihon#80] opened 2024-01-17 13:21 UTC
### Steps to reproduce

when I went to add jjk to my library I noticed it said by one it's missing 100 chapters and by the other 1771 chapters? why is that

### Expected behavior

expecting this to be fixed ngl

### Actual behavior

it should js add the chapters of if it's wrong not show up

### Mihon version

0.16.0

### Android version

android 14

### Device

Samsung galaxy s23

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment] 2024-01-17 13:24
Any chapters not visible in your current filter setting (like showing only unread chapters) will trigger this message and say that amount of chapters is missing.
There are some edge cases where the system gets tricked by a chapter being named something like "Extra - 2023 Christmas Illustration" and then believe the entry has 2023 chapters total.

While source support is out of scope for Mihon, if wherever you're getting JJK from doesn't have all chapters in the first place, those would obviously also show as missing. Some will also inevitably be incomplete for various reasons.

**Comment by 2fo2** [comment] 2024-01-17 13:25
all 4 of my extentions have the same amount of chapters and they're the latest it js gives that message

**Comment by MajorTanya** [comment] 2024-01-17 13:28
Have you filtered the list in any way? Like set it to unread only or similar?

**Comment by 2fo2** [comment] 2024-01-17 13:28
nope not that I know of

**Comment by MajorTanya** [comment] 2024-01-17 13:30
Could you provide a screenshot of the chapter list with the warning visible? Is there a warning between two chapters saying it's missing chapters between them?

**Comment by 2fo2** [comment] 2024-01-17 13:31
![Screenshot_20240117_143110_Mihon](https://github.com/mihonapp/mihon/assets/130183401/dd596d6f-a1cd-43f8-92cb-002a960eccfc)
![Screenshot_20240117_143102_Mihon](https://github.com/mihonapp/mihon/assets/130183401/5b4009b9-131f-47b0-94e4-e06eea981f5b)

**Comment by MajorTanya** [comment] 2024-01-17 13:37
Okay, for the one with over 1k missing, can you scroll through the list to see if you can find anywhere there is a warning between two chapters in the list? Would look something like this ![Screenshot_2024-01-17-14-36-24-874_eu.kanade.tachiyomi.png](https://github.com/mihonapp/mihon/assets/39014446/2a1d0813-e3a5-40cb-ab58-56e1903642ae)

**Comment by 2fo2** [comment] 2024-01-17 13:39
![Screenshot_20240117_143852_Mihon](https://github.com/mihonapp/mihon/assets/130183401/3f9a7858-ad98-41f9-acb3-64ad250e0288)
![Screenshot_20240117_143843_Mihon](https://github.com/mihonapp/mihon/assets/130183401/45d1fb6d-4560-4b44-9fd7-bf177a6fb5db)

lol wth

**Comment by MajorTanya** [comment] 2024-01-17 13:42
Ah effectively what I figured. That Jump Festa special probably has the year number in its title doesn't it 😅
That'll have caused the massive discrepancy.
As for the other one, I believe it's the name not having a number at all that's confusing the system.

Pretty sure this is on the numbering recognition system, so we'll see if someone can fix that/make it less gullible.

**Comment by 2fo2** [comment] 2024-01-17 13:43
ah okay and one other question 

is it normal the extentions need to ve "trusted" first before being used or am I js bein dumb

**Comment by MajorTanya** [comment] 2024-01-17 13:45
Yes that's normal as they're not code Mihon can express any guarantees for as its not provided by Mihon. To make users realise they're taking a risk, this trusting mechanic exists.

**Comment by 2fo2** [comment] 2024-01-17 13:46
ah so there's no danger?

**Comment by 2fo2** [comment] 2024-01-17 13:48
they're js the old tachi extentions  like repod

u want the link? or is that gonna get me banned

**Comment by TheColorman** [comment] 2024-01-17 13:49
Don't post any links, but it's hard to say whether extensions can be trusted or not, and this is probably not the place to do it. Now that extensions have gone unofficial, the people providing you extensions can make any changes they wish to them, and it is your own responsibility to ensure that they only do what they say they do.

**Comment by 2fo2** [comment] 2024-01-17 13:50
any way to check the extentions are safe? before they gobble my shi up

**Comment by TheColorman** [comment] 2024-01-17 13:51
As far as I understand, extension have to be open source by design, so you can always read through the code to make sure, but that's the same mindset you should have with everything you download off of the internet.

**Comment by 2fo2** [comment] 2024-01-17 13:53
can I say the of the place i got them from? like no links js the name

**Comment by TheColorman** [comment] 2024-01-17 13:54
I don't know but I wouldn't take any chances. The closer Mihon gets affiliated with extensions, the more likely it is to suffer the same fate as Tachi. Extensions are your own responsibility, if anything you should be talking to the people that gave them to you.

**Comment by MajorTanya** [comment] 2024-01-17 13:54
No, it's your personal responsibility and Mihon doesn't provide help with 3rd party extensions

**Comment by 2fo2** [comment] 2024-01-17 13:55
it was on github I js seached how the extention shi worked and I js put it in

**Closed** 2024-02-01 21:46 UTC
Labels: Bug
