### ISSUE TITLE
Automatic fix for Moire in pages

### ISSUE THREAD

**Issue by IDontKnow218** [mihonapp/mihon#244] opened 2024-01-27 11:01 UTC
### Describe your suggested feature

A lot of us like to download our content in high quality. The chapters (or volumes) sometimes have very high quality pages, which leads to Moire in some devices. It doesn't give us (the readers) a good reading experience, so it would be great if Mihon can automatically fix the pages and get rid of Moire.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by realFPS** [comment] 2024-02-20 07:42
[Relevant Comment](https://github.com/mihonapp/mihon/issues/42#issuecomment-1899072178)

**Comment by Smol-Ame** [comment] 2024-08-19 10:35
Closing as duplicate of #42

**Closed by Smol-Ame** 2024-08-19 10:35 UTC
Labels: Feature request
