### ISSUE TITLE
App doesn't restore entries that have errors.

### ISSUE THREAD

**Issue by THElegend5** [mihonapp/mihon#120] opened 2024-01-18 11:49 UTC
### Steps to reproduce

1. Restore a backup which contains errors.
2. Wait for it to finish restoring.

### Expected behavior

You get a notification saying there where errors in the restore.

### Actual behavior

You get a notification saying the backup restored successfully.

### Crash logs

```
2024-01-18 01:08:28.309] Why Are You Obsessed With Your Fake Wife? [Official] [Bato.to]: ResultSet returned more than 1 row for chapters.sq:getChapterByUrl
[2024-01-18 01:10:20.189] Diamond in the Rough [Komga]: ResultSet returned more than 1 row for chapters.sq:getChapterByUrl
[2024-01-18 01:43:13.074] Fables [Komga]: ResultSet returned more than 1 row for chapters.sq:getChapterByUrl
[2024-01-18 01:44:04.612] For Each Retweet, Two Straight Girls Who Don't Get Along Will Kiss for One Second - Their First Night [MangaDex]: ResultSet returned more than 1 row for chapters.sq:getChapterByUrl
```
You have to go app data folder to get the failed restore logs

### Mihon version

r6454

### Android version

Android 14

### Device

Samsung S21 FE

### Other details

https://cdn.discordapp.com/attachments/1099009853864812710/1197472596166455296/temp.proto.gz?ex=65bb6442&is=65a8ef42&hm=2207fbd9f20a63f6e6c8b1879dcef13173438953c9e66616a51ee74e91b00430&
Example backup file which contains errors only two entries will fail to restore

Also a thing to not is that before new restore logic these entries restored fine but you would get notification saying there were x errors in restore.
In versions with new logic there is no indication that these entries fail to restore.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment] 2024-01-18 12:43
This is a duplicate of #27 isn't it

**Comment by jindalpratik** [comment] 2024-01-18 12:48
> This is a duplicate of #27 isn't it

Missed that but there entries seem to still be restoring while mine don't.

**Comment by THElegend5** [comment] 2024-01-18 12:50
> This is a duplicate of #27 isn't it

Might be but their entries seem to be restoring and they seem to also get error along with it,  while mine don't restore neither do I get a error message unless I dig into the appdata folder.

**Comment by DchanN** [comment] 2024-01-18 14:22
Mine showing the error and can show error list when tap it



![Screenshot_20240118-222125357 (1)](https://github.com/mihonapp/mihon/assets/101858971/2f1024d4-6840-4bac-8097-83d70b036e20)

**Comment by MajorTanya** [comment] 2024-01-18 14:24
> Mine showing the error and can show error list when tap it
> 
> ![Screenshot_20240118-222125357 (1)](https://private-user-images.githubusercontent.com/101858971/297770228-2f1024d4-6840-4bac-8097-83d70b036e20.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1ODgxNjcsIm5iZiI6MTcwNTU4Nzg2NywicGF0aCI6Ii8xMDE4NTg5NzEvMjk3NzcwMjI4LTJmMTAyNGQ0LTY4NDAtNGJhYy04MDk3LTgzZDcwYjAzNmUyMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQxNDI0MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjk5ODRlZWM3YmZkODljZjBlYThiMzhlZTllMTQ3MzVlYmNmZWU1ZjhlMTQ1NjRiNTUwZTBjMjJjOGE2NGY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.581KjtWTEqUccHXUVr_w_L5sSsx_VHpBkDxBo6TlE94)

can you show the error log please, this doesn't help much

**Comment by DchanN** [comment] 2024-01-18 14:30
> > Mine showing the error and can show error list when tap it
> > ![Screenshot_20240118-222125357 (1)](https://private-user-images.githubusercontent.com/101858971/297770228-2f1024d4-6840-4bac-8097-83d70b036e20.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1ODgxNjcsIm5iZiI6MTcwNTU4Nzg2NywicGF0aCI6Ii8xMDE4NTg5NzEvMjk3NzcwMjI4LTJmMTAyNGQ0LTY4NDAtNGJhYy04MDk3LTgzZDcwYjAzNmUyMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQxNDI0MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjk5ODRlZWM3YmZkODljZjBlYThiMzhlZTllMTQ3MzVlYmNmZWU1ZjhlMTQ1NjRiNTUwZTBjMjJjOGE2NGY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.581KjtWTEqUccHXUVr_w_L5sSsx_VHpBkDxBo6TlE94)
> 
> can you show the error log please, this doesn't help much

error log same with thelegend and from #27 , me just comment mine show the error, because this issue said app doesn't show error

**Comment by THElegend5** [comment] 2024-01-19 11:17
Seems like you can access the errors but there is no indication in the notification that there has been an error unlike earlier versions. 
![old-version.jpg](https://github.com/mihonapp/mihon/assets/63903377/35a58264-5481-4e82-b286-8f0b321ef413)

I think the last time I tried to click it in the new version it somehow failed to bring up an option to open the error file but it does indeed open the error file in the new version even while giving no indication there has been an error.

**Comment by THElegend5** [comment] 2024-01-19 11:33
After a bit more testing and changing a couple of things in my tachiyomi library and backing up restoring mihon now does seem to be mentioning the errors so it not showing there has been errors might be a one of thing or something limited to that backup but the entries are still not being restored so updating the title to reflect that.

**Comment by AntsyLich** [comment] 2024-08-25 14:07
#647

**Closed by AntsyLich** 2024-08-25 14:07 UTC
Labels: Bug
