### ISSUE TITLE
Title change

### ISSUE THREAD

**Issue by Nekutsuu** [mihonapp/mihon#1399] opened 2024-10-28 17:33 UTC
### Describe your suggested feature

I would like a feature like in j2k where you can change the title of a manga.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-10-28 17:37
Duplicate of #5

Search the existing issues before opening a new one, and acknowledging that you did when you didn't

**Closed by Smol-Ame** 2024-10-28 17:37 UTC
Labels: Feature request
