### ISSUE TITLE
Problem When Reading Manwha/hua.

### ISSUE THREAD

**Issue by 0MikeySano** [mihonapp/mihon#1547] opened 2024-12-06 14:25 UTC
### Steps to reproduce

It happened when I updated my mihon to 0.17.0, whenever I read any manhwa it stays black but when I switch my reading mode to "Long Strip" → "Paged (left to right)" the image will only appear appear. 
![Screenshot_20241206_221347](https://github.com/user-attachments/assets/85af83fc-f795-41a5-9f1d-fbfbd52994b0)
![Screenshot_20241206_222230](https://github.com/user-attachments/assets/58b1727e-2271-47f1-9305-b8dcad6c5ece)

### Expected behavior

This shouldn't happen when reading any manhwa/hua.

### Actual behavior

As I said earlier it happened when I updated mihon to latest, but before I update it I can still read manhwa/hua.

### Mihon version

0.17.0

### Android version

Android 8

### Device

Vivo

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-12-06 14:59
Duplicate of closed #1436 and ongoing issue of #1541

It's already been reported before. Search the existing issues first before opening a new one, and acknowledging that you did when you clearly didn't.

**Closed by Smol-Ame** 2024-12-06 14:59 UTC
Labels: Bug
