### ISSUE TITLE
App crash loop

### ISSUE THREAD

**Issue by x84yr41** [mihonapp/mihon#640] opened 2024-04-09 03:05 UTC
### Steps to reproduce

Open the Mihon app

### Expected behavior

Should display the library as the first page 
![Screenshot_20240409-105718](https://github.com/mihonapp/mihon/assets/82630193/e63b5fc2-5308-4e51-a1ae-ed85d8035700)

### Actual behavior

Crash loop happens. It shows a crash log but no way to check since it the app exits then start again with the same crash message error immediately. 

### Mihon version

0.16.14

### Android version

Android 14

### Device

Google Pixel 6

### Other details

![Screenshot_20240409-105718](https://github.com/mihonapp/mihon/assets/82630193/5508fae9-c6a6-4ad7-b0aa-aaa3d2d2d2a6)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment] 2024-04-09 03:06
Duplicate of #639, #624, #623, #616, #582, #363. Please search issues before opening new ones.

**Closed by MajorTanya** 2024-04-09 03:06 UTC
Labels: Bug
