### ISSUE TITLE
Local Sync/Auto-Restore

### ISSUE THREAD

**Issue by Lobuttomize** [mihonapp/mihon#981] opened 2024-07-04 16:01 UTC
### Describe your suggested feature

A way to sync without requiring an account or anything. You would have the app create its auto-backup to a folder that is either shared on a network or connected to something like Dropbox. The sync or auto-restore feature would then sync with the backup in the designated location whenever the app is launched. There would presumably need to be a way for the app to know which backup (since multiple devices would be auto-backing up) is the most up-to-date, but I'm not personally a programmer so I'm not sure the ideal way to implement something like that. Perhaps just running the backup and then the sync on app launch so it can choose the most recent.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2024-07-05 23:45
Duplicate of #812

**Closed by AntsyLich** 2024-07-05 23:45 UTC
Labels: Feature request
