### ISSUE TITLE
Updating library not working -fixed

### ISSUE THREAD

**Issue by SirArthurConan** [mihonapp/mihon#276] opened 2024-01-29 17:25 UTC
### Steps to reproduce

Updating library just didn't work for me, but then I turned off smart update and now it works. There's a issue with smart update. I had predict next release time on, updating didn't work, the second I turned it off, I can update my library. 

### Expected behavior

Library should still update. 

### Actual behavior

Library not updating. 

### Mihon version

0.16.0, 0.16.1 and 0.16.2

### Android version

Android 14

### Device

Google Pixel 6a

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.2](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment] 2024-01-29 17:35
Not an issue, that is intended/expected behaviour of the smart updates & predict next chapter release settings.
There is no issue here, as Mihon tries to _predict_ when the next chapter is likely to be released, and it doesn't bother asking the source about new chapters until its predicted date rolls around.
This helps lessen source load and unnecessary requests.

Closing as the feature is intended. If you have further questions, ask in the #support channel on the Mihon Discord.

**Closed by MajorTanya** 2024-01-29 17:35 UTC
Labels: Bug
