### ISSUE TITLE
Add title from webview to library

### ISSUE THREAD

**Issue by Character95** [mihonapp/mihon#955] opened 2024-06-26 14:22 UTC
### Describe your suggested feature

Add option to add title from webview to library so that it doesnt need to be copied and searched again to add to library

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2024-06-26 14:57
Duplicate of #853

**Closed by AntsyLich** 2024-06-26 14:57 UTC
Labels: Feature request
