### ISSUE TITLE
http 503 error on mal tracker 

### ISSUE THREAD

**Issue by Key-explanation** [mihonapp/mihon#312] opened 2024-02-01 04:53 UTC
### Steps to reproduce

1. Open a manga that you want to track
2. Click on the mal tracker
3. It would show http 503 error

### Expected behavior

Should show the manga from mal

### Actual behavior

Showing Http error 503 

### Crash logs

App version: 0.16.3-6499 (standard, 139663acf, 4, 2024-01-29T20:34Z)
Android version: 11 (SDK 30; build RP1A.200720.012 release-keys)
Device brand: vivo
Device manufacturer: vivo
Device name: 1901 (1901)
Device model: vivo 1901
WebView: Android System WebView 120.0.6099.230

--------- beginning of main
02-01 09:26:56.433 25346 25346 E app.mihon.debu: Not starting debugger since process cannot load the jdwp agent.
02-01 09:26:57.337 25346 25400 E SQLiteLog: (283) recovered 233 frames from WAL file /data/data/app.mihon.debug/databases/tachiyomi.db-wal
02-01 09:26:59.112 25346 25473 E chromium: [0201/092659.111910:ERROR:variations_seed_loader.cc(37)] Seed missing signature.
02-01 09:27:04.378 25346 25717 E SQLiteLog: (284) automatic index on C(manga_id)
02-01 09:27:04.378 25346 25717 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
02-01 09:32:26.696 25346 25751 E ion     : ioctl c0044901 failed with code -1: Invalid argument
02-01 09:32:26.696 25346 25727 E ion     : ioctl c0044901 failed with code -1: Invalid argument
02-01 09:32:26.734 25346 25751 E ion     : ioctl c0044901 failed with code -1: Invalid argument
02-01 10:21:32.752  9251  9251 E app.mihon.debu: Not starting debugger since process cannot load the jdwp agent.
02-01 10:21:34.580  9251  9334 E chromium: [0201/102134.579878:ERROR:variations_seed_loader.cc(37)] Seed missing signature.
02-01 10:21:38.496  9251  9589 E SQLiteLog: (284) automatic index on C(manga_id)
02-01 10:21:38.497  9251  9589 E SQLiteLog: (284) automatic index on mangas_categories(manga_id)
02-01 10:21:38.648  9251  9294 E ion     : ioctl c0044901 failed with code -1: Invalid argument
02-01 10:21:39.492  9251  9563 E ion     : ioctl c0044901 failed with code -1: Invalid argument
02-01 10:21:39.493  9251  9566 E ion     : ioctl c0044901 failed with code -1: Invalid argument

### Mihon version

0.16.3

### Android version

Android 11 

### Device

Vivo Y15

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment] 2024-02-01 05:10
Duplicate of #298, MAL is currently experiencing API issues and has deactivated their manga related API endpoints until further notice.

**Closed by MajorTanya** 2024-02-01 05:10 UTC
Labels: Bug

**Comment by masdabazz** [comment] 2024-02-01 17:57
Hi, so is this something that will be fixed once MAL has resolved everything?

**Comment by MajorTanya** [comment] 2024-02-01 18:19
> Hi, so is this something that will be fixed once MAL has resolved everything?

1. Please don't comment on duplicates, do so at the issue I linked above.
2. Tracking _should_ function as normal once MAL lifts their manga API lockdown again.
