### ISSUE TITLE
It might just suddenly quit without knowing the situation.

### ISSUE THREAD

**Issue by chen274** [mihonapp/mihon#1327] opened 2024-10-15 02:39 UTC
### Steps to reproduce

I don't know how. I just stop working

### Expected behavior

Normal operation

### Actual behavior

Stop working

### Crash logs

[mihon_crash_logs(1).txt](https://github.com/user-attachments/files/17371805/mihon_crash_logs.1.txt)

### Mihon version

0.16.5

### Android version

Android 14

### Device

Xiaomi 13pro

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2024-10-15 02:44
Duplicate of #1278

**Closed by AntsyLich** 2024-10-15 02:44 UTC
Labels: Bug
