### ISSUE TITLE
All pages after page 1 are balnk in long strip reading modes

### ISSUE THREAD

**Issue by Rudikolo** [mihonapp/mihon#1398] opened 2024-10-28 17:17 UTC
### Steps to reproduce

1. Open any manhwa
2. reading mode is long strip/ long strip with gaps.
3. Scroll down

### Expected behavior

Read Normaly
![IMG-20241028-WA0007](https://github.com/user-attachments/assets/ed121e6b-f896-4870-833e-b0d425fc0db9)
![IMG-20241028-WA0009](https://github.com/user-attachments/assets/3c4c8e21-b35e-43cd-9f0a-2e7b6f4530c3)
![IMG-20241028-WA0008](https://github.com/user-attachments/assets/3aecba06-8d5d-4d65-92a0-ac4148c60a95)

### Actual behavior

Blank pages after page 1
![IMG-20241028-WA0011](https://github.com/user-attachments/assets/58d80b1d-56bc-4861-8f50-a7d0e0890580)
![IMG-20241028-WA0006](https://github.com/user-attachments
![IMG-20241028-WA0005](https://github.com/user-attachments/assets/e44881c6-e6eb-4dab-a6dd-e23f24f3532c)
/assets/dd2ff3b1-4c36-43a2-9a6e-731e76912f06)
![IMG-20241028-WA0004](https://github.com/user-attachments/assets/fc309566-ddba-4fcb-a420-f4bd5414f7f6)

### Mihon version

0.17.0

### Android version

Android 8.0.0

### Device

Samsung Galaxy S7 edge

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2024-10-29 05:03
We need someone patient who is affected with the issues to help out with the diagnosis. Please come to our discord server if you wish to help.

**Comment by Specter643** [comment] 2024-10-29 05:10
I've been facing the same problem after the update which made me stop reading for 2. I've tried changing settings but the issue is still there. I ask the developers to please fix this issue ASAP.

**Comment by Raikuha** [comment] 2024-10-29 06:23
I only noticed this issue with very few webtoons, sometimes affecting one chapter but not others. In some cases like Magic Emperor, ch 610 (manga demon source) the issue is a constant flickering as you scroll down that may be fixed by zooming out. In others like The Last Adventurer, ch 41 I think, from Asura source, the black was like a big gap between the images. I don't remember if it had flickering as well, but I can probably check.

**Comment by PrParadoxy** [comment] 2024-10-29 19:19
This is replicate of https://github.com/mihonapp/mihon/issues/1390. None of the suggested workarounds work. 

> On Samsung Galaxy 2016, I also have the same issue. If the problem is device being old, then how come on 0.16.5 version we do not have this exact problem? Split image doesn't solve the problem, neither downloading the images ahead. The paged reader doesn't bring smooth experience for Webtoons and many manhwas. Something in version 0.17 broke the reader, and it is a pitty since we cannot update mihon app beyond 0.16.5 anymore.
> Would it be possible to add a button that reverts the reader to its 0.16.5 version for older devices? Or alternatively, a "long strip legacy" as an extra option for people like us.

**Closed** 2024-10-31 13:21 UTC
Labels: Bug
