### ISSUE TITLE
Manually change series from Ongoing to Completed (etc.)

### ISSUE THREAD

**Issue by jbam17** [mihonapp/mihon#1408] opened 2024-10-30 01:40 UTC
### Describe your suggested feature

It would be nice to be able to manually change a series to completed instead of ongoing, because many of my library series get marked as ongoing and show up in the smart updates and upcoming sections even if they're way past done.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by BrutuZ** [comment] 2024-10-30 01:44
> - [ ] I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open or closed issue.

No, you haven't. But as a solution before this is closed as duplicate, you can add those entries to a category and exclude it from Global Updates

**Comment by MajorTanya** [comment] 2024-10-30 01:46
Duplicate of #5

**Closed by MajorTanya** 2024-10-30 01:46 UTC
Labels: Feature request

**Comment by Animeboynz** [comment] 2024-10-30 01:50
Technically not a duplicate #5 and #398 have nothing about manga status.

**Comment by MajorTanya** [comment] 2024-10-30 01:53
#782 requested the same thing and was closed as a duplicate of #5.

**Comment by Animeboynz** [comment] 2024-10-30 01:54
I see I see

**Comment by jbam17** [comment] 2024-10-30 16:20
I am mostly talking about the upcoming tab, and the others didn't reference it. I really just want a way to make my upcoming tab more clean to see estimated releases. Maybe an option to only exclude a series from the upcoming calendar tab?

**Comment by jbam17** [comment] 2024-10-30 16:22
I already tried excluding from global updates like suggested but that doesn't take them out from the upcoming tab...
