### ISSUE TITLE
Contains in chapter are all black

### ISSUE THREAD

**Issue by Author002** [mihonapp/mihon#1390] opened 2024-10-27 16:44 UTC
### Steps to reproduce

https://github.com/user-attachments/assets/c031461d-1824-4c28-b4c0-c846e6b7046a

![Screenshot_2024-10-27-22-20-19-598_app mihon](https://github.com/user-attachments/assets/42b3a567-2419-4743-bb14-834131e8f682)
![Screenshot_2024-10-27-22-20-14-181_app mihon](https://github.com/user-attachments/assets/2dff73ef-b674-47e7-8bd2-10df175b00c5)
![Screenshot_2024-10-27-22-19-56-987_app mihon](https://github.com/user-attachments/assets/5ab85ff2-0430-4c76-8da9-01a50172f162)

### Expected behavior

All contains are black 

### Actual behavior

Can't read anything 😔

### Mihon version

0.17.0

### Android version

Android 10

### Device

Redmi dual 8A

### Other details

As shown in scree record this is happening with in everything,it just doesn't show contains of any of my mangas and manwas 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Author002** [comment] 2024-10-27 17:52
> Ohh I thought my emulator just bugging out I was able to fix this bug earlier in my bluestacks I change my resolution. so it's not the emulator having the problem.

Help me with it brother 😭

**Comment by Animeboynz** [comment] 2024-10-27 18:04
Looks like the images are just loading a little slow, try pairing downloads ahead and delete after read so it's predownloaded before you start reading.

**Comment by Author002** [comment] 2024-10-27 18:09
> Looks like the images are just loading a little slow, try pairing downloads ahead and delete after read so it's predownloaded before you start reading.

It will be pretty annoying to download every chapter to read😢

**Comment by MajorTanya** [comment] 2024-10-27 18:12
> > Looks like the images are just loading a little slow, try pairing downloads ahead and delete after read so it's predownloaded before you start reading.
> 
> It will be pretty annoying to download every chapter to read😢

That's what the "Download Ahead" feature would be doing for you. And "delete after read" would make sure you don't accumulate lots of chapters you've already read that take up storage space.

**Comment by Author002** [comment] 2024-10-27 18:35
> > > Looks like the images are just loading a little slow, try pairing downloads ahead and delete after read so it's predownloaded before you start reading.
> > 
> > 
> > It will be pretty annoying to download every chapter to read😢
> 
> That's what the "Download Ahead" feature would be doing for you. And "delete after read" would make sure you don't accumulate lots of chapters you've already read that take up storage space.

I think I get what happened 
It just my my phone just gave up loading image because it was too much for it to handle 😭
I checked with my newer model mobile and it's just working fine 😢

**Comment by Smol-Ame** [comment] 2024-10-27 18:35
Duplicate of many, but recently closed #1388

Really long/large pages have issues displaying on weaker/older devices, do the following:
* Go to Mihon Settings > Downloads, enable "Split tall images" (this setting is not retroactive, redownload the chapter if it's already downloaded)
* Download the chapter
* Should load up the long/large pages better

Otherwise, another solution is to switch the reading mode to Paged

**Comment by Smol-Ame** [comment] 2024-10-27 18:36
Stop playing with the close & open button

**Closed by Smol-Ame** 2024-10-27 18:35 UTC
Labels: Bug

**Comment by Author002** [comment] 2024-10-27 18:37
> Stop playing with the close & open button

Sorry 😅

**Comment by PrParadoxy** [comment] 2024-10-28 16:28
@Smol-Ame On Samsung Galaxy 2016, I also have the same issue. If the problem is device being old, then how come on 0.16.5 version we do not have this exact problem? Split image doesn't solve the problem, neither downloading the images ahead. The paged reader doesn't bring smooth experience for Webtoons and many manhwas. Something in version 0.17 broke the reader, and it is a pitty since we cannot update mihon app beyond 0.16.5 anymore.
