### ISSUE TITLE
Funcion for enable the "two pages" in landscape mode

### ISSUE THREAD

**Issue by epsilons9** [mihonapp/mihon#174] opened 2024-01-21 13:47 UTC
### Describe your suggested feature

![Screenshot](https://github.com/mihonapp/mihon/assets/147890479/a893ac60-1b69-4e4d-9564-db3e3888c83f)

I think it would be interesting to have this function, both for those who use cell phones and tablets (the image is an example of what I'm talking about).  I understand that the application is constantly changing and updating, and I am grateful that this project exists. Thank you for the attention.

### Other details

None.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2024-01-21 13:48
Duplicate of #28

**Closed by AntsyLich** 2024-01-21 13:48 UTC
Labels: Feature request
