### ISSUE TITLE
Add Trust all button

### ISSUE THREAD

**Issue by WGmg23** [mihonapp/mihon#249] opened 2024-01-27 23:34 UTC
### Describe your suggested feature

add trusted button for all extension

### Other details

....

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment] 2024-01-27 23:35
Direct duplicate of #183 and covered in several other issues already. Please check before filing duplicate requests.

**Closed** 2024-01-28 05:44 UTC
Labels: Feature request
