### ISSUE TITLE
Can you increase backup to webdav and recover from Webdav

### ISSUE THREAD

**Issue by wbmins** [mihonapp/mihon#614] opened 2024-04-02 01:09 UTC
### Describe your suggested feature

Can you increase backup to webdav and recover from Webdav

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.

- [ ] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.

- [X] I will fill out all of the requested information in this form.

**Comment by loocool2** [comment] 2024-04-02 04:23
Duplicate of #472

**Closed** 2024-05-04 11:06 UTC
Labels: Feature request
