### ISSUE TITLE
Error badge on tile when update failed

### ISSUE THREAD

**Issue by BerenOneHand** [mihonapp/mihon#1180] opened 2024-08-30 14:26 UTC
### Describe your suggested feature

When running an update and the request failed, show a badge on the tile. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-08-30 16:28
Closing as a duplicate of closed #686 to follow previous ruling

**Closed by Smol-Ame** 2024-08-30 16:28 UTC
Labels: Feature request
