### ISSUE TITLE
After upgrading the extensions still shows updates pending

### ISSUE THREAD

**Issue by arfannn88** [mihonapp/mihon#184] opened 2024-01-22 03:09 UTC
### Steps to reproduce

After upgrading the extension still shows updates pending. Currently we need to exit the app then go inside extensions than refresh then trust extensions to fix this problem.

### Expected behavior

The pending should not appear after upgrade.

### Actual behavior

After upgrading the extension still shows updates pending. Currently we need to exit the app then go inside extensions than refresh then trust extensions to fix this problem.

### Mihon version

0.16.1

### Android version

All version

### Device

All android device

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Shawkik-Islam-Joha** [comment] 2024-01-22 03:33
Same issue happening on my -
Android 12
MIUI 13
Redmi Note 9
As far as I know, It's happening in all Android devices.

**Comment by AntsyLich** [comment] 2024-01-22 04:45
Duplicate of #179

**Closed by AntsyLich** 2024-01-22 04:45 UTC
Labels: Bug
