### ISSUE TITLE
Reading Mode based on Categories

### ISSUE THREAD

**Issue by riki270601** [mihonapp/mihon#1526] opened 2024-11-29 10:43 UTC
### Describe your suggested feature

Implement a "Reading Mode" feature that organizes and displays content based on specific categories. for example i want longstrip reading mode for Manhwa categories

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.17.0](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2024-11-29 10:55
Duplicate of #247

**Closed by AntsyLich** 2024-11-29 10:55 UTC
Labels: Feature request
