### ISSUE TITLE
Double tap to exit

### ISSUE THREAD

**Issue by Key-explanation** [mihonapp/mihon#173] opened 2024-01-21 11:28 UTC
### Describe your suggested feature

It was a feature that Tachiyomi had where you would double press to exit the app. I have searched every settings options and could not find it

### Other details

.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.16.1](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment] 2024-01-29 00:10
This feature was removed in 8f4bc71cf7b99fe0b0d2ea68dfca0140477686cc because it was deemed redundant with Android's Predictive Back feature when using gesture navigation, just to assure you it used to exist. 👍

I don't know if there would be a way to bring this feature back that doesn't clash with this predictive back feature, though, so I can't give you a definitive yes/no on whether it can be brought back.

**Comment by MajorTanya** [comment] 2024-01-29 04:07
Update: I just saw that this is a duplicate of #91, so I will be closing this issue and copying my comment on that issue.

**Closed by MajorTanya** 2024-01-29 04:07 UTC
Labels: Feature request
