### ISSUE TITLE
Batch un-setting categories crashes the app

### ISSUE THREAD

**Issue by infyProductions** [mihonapp/mihon#813] opened 2024-05-20 04:01 UTC
### Steps to reproduce

1. Start Mihon (either the latest stable or latest preview)
2. Mark at least two entries in your library
3. Tap "Set Categories" (the action button on the bottom left)
4. Untick the category (in my case, I'm currently removing finished entries in one of the categories)
5.  Tap OK

### Expected behavior

_Hopefully_ doesn't crash

### Actual behavior

Stable 0.16.5:
![Screenshot_2024-05-20-11-23-41-37_551f7f0ca926862b368845ce7ee433aa](https://github.com/mihonapp/mihon/assets/31158494/ff2725ae-f5df-40c5-8d45-2b8555c77cb3)
Beta r6697:
![Screenshot 2024-05-20 112450](https://github.com/mihonapp/mihon/assets/31158494/2f6af405-7b53-44ab-a3d3-e25c02936c63)

### Crash logs

Logs from the stable build:
[Stable 0.16.5 mihon_crash_logs.txt](https://github.com/mihonapp/mihon/files/15372421/Stable.0.16.5.mihon_crash_logs.txt)
Logs from the latest beta build:
[Beta 0.16.5-6697_mihon_crash_logs.txt](https://github.com/mihonapp/mihon/files/15372424/Beta.0.16.5-6697_mihon_crash_logs.txt)

### Mihon version

Stable 0.16.5/Beta r6697

### Android version

Android 11 (for stable)/Android 13 (for beta)

### Device

Realme 6i (used in stable)/WSA version 2311.40000.5.0 (used in beta)

### Other details

When batch adding entries to another category, it doesn't crash the app; only happens when you remove the entry from that category.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by infyProductions** [comment] 2024-05-20 05:46
Additional Info: While it crashes the app by unsetting the category of two or more entries, it seems to bizarrely work.

Here's an example with a filtered category (Completed) with a total of 25 entries:
![image](https://github.com/mihonapp/mihon/assets/31158494/953945f2-5274-4df3-b5df-f14ab5219a64)

**Comment by THElegend5** [comment] 2024-05-20 07:47
Duplicate of #93

**Closed** 2024-08-14 21:13 UTC
Labels: Bug
