### ISSUE TITLE
Show the latest Chapter # when migrating

### ISSUE THREAD

**Issue by Firestorm808** [mihonapp/mihon#355] opened 2024-02-06 22:13 UTC
### Describe your suggested feature

When you migrate, it'll show lists from extensions 1, 2, etc. In addition to the cover and title, the latest chapter # will be given.

Let's say I have Series A up to Chapter 100 From Extension A.

When Migrating, it would show:

Extension A
Series A, Cover, Title, Chapter 100 | 

Extension B
Series A, Cover, Title, Chapter 125 | Series B, Cover, Title, Chapter # | 

Extension C
Series A, Cover, Title, Chapter 50 | Series B, Cover, Title, Chapter # | 

Extension D
Series A, Cover, Title, Chapter 90 | Series B, Cover, Title, Chapter # | 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.3](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by AntsyLich** [comment] 2024-02-06 22:16
Duplicate of #324

**Closed by AntsyLich** 2024-02-06 22:16 UTC
Labels: Feature request

**Comment by BrutuZ** [comment] 2024-02-06 22:17
> - [ ] I have searched the existing issues and this is a new ticket, NOT a duplicate or related to another open or closed issue.

Duplicate of #324

**Comment by Firestorm808** [comment] 2024-02-06 22:18
Apologies for the oversight.
