### ISSUE TITLE
Extension update bug

### ISSUE THREAD

**Issue by poliglesias** [mihonapp/mihon#1245] opened 2024-09-19 08:58 UTC
### Steps to reproduce

-I have extensions to update
-i update them
-the extension has the newer version
-still appearing on pending updates

### Expected behavior

Disappear from pending updates

### Actual behavior

Keeps showing as pending update

### Mihon version

0.16.5

### Android version

13

### Device

Xiaomi pad 5

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-09-19 09:02
Duplicate of many, too lazy to find them, search Xiaomi & you might get a good handful of results.

For Xiaomi **MIUI OS** & **HyperOS** users:
* Go to your Phone Settings > Developer Options, and __turn off system optimization/MIUI Optimization__
> If you don't see this setting:
> * Scroll down to the bottom of Developer Options
> * Tap multiple times on "Reset to default values" until it appears
** **
Extra step for Xiaomi **HyperOS** users:
> This extra permission is only on __certain regional versions of HyperOS__, if you don't see this optional permission, ignore this portion of the message.
* Go to Mihon app info (not in-app)
* Go into Permissions > Other Permissions > Access List of Installed Apps, and set it to "Always Allow"

If that doesn't help, check with whoever maintains your extensions for help or come to Mihon Discord support channel and reference your GitHub issue in there

**Closed by Smol-Ame** 2024-09-19 09:02 UTC
Labels: Bug
