### ISSUE TITLE
Option to save filter options for an extension

### ISSUE THREAD

**Issue by User89182** [mihonapp/mihon#1344] opened 2024-10-18 11:34 UTC
### Describe your suggested feature

Save filter settings for an extension. So don't have to set the filter each time i click on it. It's stressful everyday manually setting filters each time.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Animeboynz** [comment] 2024-10-18 12:02
Duplicate of #992, #33 & #164???

**Comment by MajorTanya** [comment] 2024-10-18 12:04
Duplicate of #164

**Closed by MajorTanya** 2024-10-18 12:04 UTC
Labels: Feature request
