### ISSUE TITLE
Mihon take long to load .cbz offline manga

### ISSUE THREAD

**Issue by leonminus** [mihonapp/mihon#735] opened 2024-05-01 18:48 UTC
### Steps to reproduce

Read downloaded to .cbz offline manga

### Expected behavior

When read offline .cbz the app like to load the website script before check offline file .cbz
But even i turn off wifi n data 4g it still loading and take long time to load the manga. Sometime i have to quit the manga title to library, sometime have ti restart the whole app

### Actual behavior

Read fast like immediately when in previous Mihon (or Tachi) version

### Crash logs

Noth

### Mihon version

0.16.5

### Android version

Android 11

### Device

Vivo y21 4g ran

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have gone through the [FAQ](https://mihon.app/docs/faq/general) and [troubleshooting guide](https://mihon.app/docs/guides/troubleshooting/).
- [X] I have updated the app to version **[0.16.5](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by MajorTanya** [comment] 2024-05-01 21:59
Do you happen to have a large amount of chapters downloaded?

**Comment by FooIbar** [comment] 2024-05-02 03:34
Sounds like a duplicate of #134, which has been fixed in mihon preview.

**Comment by FooIbar** [comment] 2024-05-02 13:41
See #705

**Comment by leonminus** [comment] 2024-05-02 13:53
> See #705

ok so i dont really get anything about the system but sound like this app not able to deal with 1000+ manga download even in .cbz file or not, u tell me if im wrong someth? if so then i'll wait h dev and close this issue 8))

**Comment by MajorTanya** [comment] 2024-05-02 13:55
> > See #705
> 
> ok so i dont really get anything about the system but sound like this app not able to deal with 1000+ manga download even in .cbz file or not, u tell me if im wrong someth? if so then i'll wait h dev and close this issue 8))

You are right, Mihon struggles when there are a lot of downloaded chapters. Whether they are images or in a .cbz doesn't matter for the struggling. For now, I can only recommend checking out the "Download Ahead" setting in Mihon, and deleting chapters after you've read them.

**Comment by leonminus** [comment] 2024-05-02 14:01
> > > See #705
> > 
> > 
> > ok so i dont really get anything about the system but sound like this app not able to deal with 1000+ manga download even in .cbz file or not, u tell me if im wrong someth? if so then i'll wait h dev and close this issue 8))
> 
> You are right, Mihon struggles when there are a lot of downloaded chapters. Whether they are images or in a .cbz doesn't matter for the struggling. For now, I can only recommend checking out the "Download Ahead" setting in Mihon, and deleting chapters after you've read them.

i get it, thank you sir.

**Closed** 2024-05-02 14:01 UTC
Labels: Bug
