### ISSUE TITLE
Library setting

### ISSUE THREAD

**Issue by srcsvl** [mihonapp/mihon#456] opened 2024-02-26 23:00 UTC
### Describe your suggested feature

It would be nice if we could group the sources of the manga we add to the library separately according to their source.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.16.4](https://github.com/mihonapp/mihon/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Smol-Ame** [comment] 2024-08-19 10:35
Duplicate of #378

**Closed by Smol-Ame** 2024-08-19 10:35 UTC
Labels: Feature request
